//! **G_FLOAT_AFTER_INLINE_TEXT — a float written after text on a line belongs at that line box's
//! TOP, not below it (CSS 2.1 §9.5 rule 6) — provided it still FITS on that line.**
//!
//! > *"The outer top of a floating box may not be higher than the top of any line-box containing a
//! > box generated by an element earlier in the source document."*
//!
//! That is a bound on the line's **top**. We flushed the pending inline run — which advances past
//! the whole run — and then placed the float below it, so every such float came out **one
//! line-height too low** and dragged its entire exclusion band down with it.
//!
//! `<img class="alignright">` inside a paragraph is exactly this shape, and it is the most common
//! float on the content web: the WordPress/CMS idiom, every news article's inline photo, every
//! documentation callout.
//!
//! Measured against `google-chrome-stable --headless=new --hide-scrollbars --window-size=1200,800`,
//! `(x, y)` of the float with `y` relative to its container:
//!
//! ```text
//!                                                          Chrome      before      after
//!   #s1  the float FIRST, then text                       [  0,  0]   [  0,  0]   [  0,  0]
//!   #s2  text, then the float (one line)                  [  0,  0]   [  0, 20]   [  0,  0]
//!   #s3  a <p> BLOCK, then the float                      [  0, 52]   [  0, 52]   [  0, 52]
//!   #s4  text wrapping to TWO lines, then the float       [  0, 20]   [  0, 40]   [  0, 20]
//!   #s5  text, then a float:RIGHT                         [260,  0]   [260, 20]   [260,  0]
//!   #s7  a 20px float, then text, then a second float     [ 40,  0]   [  0, 20]   [ 40,  0]
//!   #s8  line-height: 40px, text, then the float          [  0,  0]   [  0, 40]   [  0,  0]
//!   #s9  text<br>second, then the float                   [  0, 20]   [  0, 40]   [  0, 20]
//!   #s10 text, then a float TOO WIDE for the line         [  0, 40]   [  0, 40]   [  0, 40]
//! ```
//!
//! ## `#s10` is the other half of the rule, and a top-bound alone breaks it
//!
//! ⚠⚠⚠ A 280px float after text in a 300px block goes on the **next** line in Chrome. My first fix
//! was the top-bound alone and it moved this row from right to **wrong** — 9/10, having started at
//! 6/10. `FloatContext::place` cannot decide it: `place` scans bands of **floats**, and what is in
//! the way here is the line's own already-placed **inline content**, which is not a float and is not
//! in the context at all. So the line's remaining width is measured from the fragments, and a float
//! too wide for it starts below the run exactly as it used to.
//!
//! **A rule quoted from the spec is half a rule until the row where it must NOT apply is written.**
//!
//! ## `#s3` and `#s7` are what keep it from being "floats go to y = 0"
//!
//! ⚠⚠ `#s3` has a *block* before the float, so there is no pending line and the float stays at 52.
//! `#s7` has a real float already occupying `x = 0..40` at that same `y`, and the second float goes
//! **beside** it at `x = 40, y = 0` rather than below — so the band search still runs from the new
//! starting point rather than being replaced by it. Without these two rows, "place every float at
//! the top of its container" passes every other row here.
//!
//! ## RED proof (run, not imagined)
//!
//! Passing `None` for `line_fit` into `layout_float` — the pre-fix behaviour — gives
//! `#s2 (0, 20), Chrome gives (0, 0)`. `#s1`, `#s3` and `#s10` keep passing under that revert, which
//! is what makes them controls.

use manuk_text::FontContext;

/// Every container is its own BFC, so a float can never leak into the next row and make this
/// fixture measure the wrapper instead (the failure mode that cost a whole battery at t1000).
const HTML: &str = r##"<!doctype html><html><head><style>
 body{margin:0;font:16px/20px monospace}
 .g{background:#eee;width:300px;overflow:hidden;margin-bottom:8px}
 .fl{float:left;width:40px;height:50px;background:#c00}
 .fr{float:right;width:40px;height:50px;background:#00c}
</style></head><body>
<div class="g" id="n1"><div class="fl" id="s1"></div>text</div>
<div class="g" id="n2">text<div class="fl" id="s2"></div></div>
<div class="g" id="n3"><p>para</p><div class="fl" id="s3"></div></div>
<div class="g" id="n4">aaa bbb ccc ddd eee fff ggg hhh iii jjj kkk lll mmm<div class="fl" id="s4"></div>zzz</div>
<div class="g" id="n5">text<div class="fr" id="s5"></div></div>
<div class="g" id="n6">text<span>more</span><div class="fl" id="s6"></div>tail</div>
<div class="g" id="n7"><div class="fl" style="height:20px"></div>text<div class="fl" id="s7"></div></div>
<div class="g" id="n8" style="line-height:40px">text<div class="fl" id="s8"></div></div>
<div class="g" id="n9">text<br>second<div class="fl" id="s9"></div></div>
<div class="g" id="n10">aaa bbb ccc ddd eee fff ggg hhh iii jjj kkk lll mmm nnn ooo<div class="fl" id="s10" style="width:280px"></div>zzz</div>
</body></html>"##;

fn rect(page: &manuk_page::Page, id: &str) -> (i64, i64) {
    let dom = page.dom();
    let n = manuk_css::query_selector_all(dom, dom.root(), &format!("#{id}"))
        .first()
        .copied()
        .unwrap_or_else(|| panic!("#{id} matched nothing"));
    let b = *page
        .root_box
        .node_rects(dom)
        .get(&n)
        .unwrap_or_else(|| panic!("#{id} has no box — it was not laid out at all"));
    (b.x.round() as i64, b.y.round() as i64)
}

/// `(x, y)` with `y` relative to the container — the containers are stacked, so an absolute `y`
/// would encode the fixture's ordering rather than the claim.
fn at(page: &manuk_page::Page, container: &str, id: &str) -> (i64, i64) {
    let (x, y) = rect(page, id);
    (x, y - rect(page, container).1)
}

fn check(page: &manuk_page::Page, container: &str, id: &str, want: (i64, i64), why: &str) {
    let got = at(page, container, id);
    assert_eq!(
        got, want,
        "G_FLOAT_AFTER_INLINE_TEXT: #{id} is at {got:?} within #{container}, Chrome gives \
         {want:?}.\n  {why}"
    );
}

#[test]
fn a_float_after_inline_text_sits_at_that_lines_top() {
    let fonts = FontContext::new();
    let page = manuk_page::Page::load(HTML, "https://floatline.test/", &fonts, 1200.0);

    // ── 0. CONTROLS FIRST. These passed before the fix and must pass after; they are what stop the
    //    rule from degenerating into "a float goes at the top of its container".
    check(
        &page,
        "n1",
        "s1",
        (0, 0),
        "control: the float comes FIRST, so there is no pending line and nothing to join",
    );
    check(
        &page,
        "n3",
        "s3",
        (0, 52),
        "control: a <p> BLOCK precedes the float, so again there is no pending line — the float \
         stays below the block. \"Every float goes to y=0\" fails here and passes everything else",
    );

    // ── 1. THE DEFECT.
    check(
        &page,
        "n2",
        "s2",
        (0, 0),
        "text, then the float: rule 6 bounds the float by the line's TOP, and we used its BOTTOM — \
         one line-height too low, with the whole exclusion band dragged down with it",
    );
    check(
        &page,
        "n6",
        "s6",
        (0, 0),
        "…and an inline <span> between them changes nothing — it is the same line box",
    );

    // ── 2. IT IS THE *LAST* LINE'S TOP, WHICH ONLY A WRAPPING RUN CAN SHOW.
    check(
        &page,
        "n4",
        "s4",
        (0, 20),
        "the text wraps to TWO lines, so the float joins the line it is actually IN — y=20, not 0 \
         and not 40. A run that fits on one line cannot tell those three apart",
    );
    check(
        &page,
        "n9",
        "s9",
        (0, 20),
        "…and an explicit <br> gives the same answer, so it is the line box and not word wrapping",
    );
    check(
        &page,
        "n8",
        "s8",
        (0, 0),
        "`line-height: 40px` — the float is at the line's TOP whatever the line's height is. If the \
         fix had been \"subtract one line-height\" this row would read -20 or 40",
    );

    // ── 3. THE SIDE IS NOT THE POINT. A right float has exactly the same bound.
    check(
        &page,
        "n5",
        "s5",
        (260, 0),
        "a float:right after text: its x was always correct and its y had the same defect, so this \
         is a line-box rule and not a side-specific one",
    );

    // ── 4. THE BAND SEARCH STILL RUNS. The new top is a starting point, not a placement.
    check(
        &page,
        "n7",
        "s7",
        (40, 0),
        "a 20px float already occupies x=0..40 on this line, so the second float goes BESIDE it at \
         x=40 — same y, further right. If the fix had replaced the search rather than moved its \
         start, this reads (0, 0) and overlaps",
    );

    // ── 5. THE OTHER HALF OF THE RULE, and the row my first fix broke.
    check(
        &page,
        "n10",
        "s10",
        (0, 40),
        "a 280px float after text in a 300px block does NOT join that line — it does not fit beside \
         what is already on it, and Chrome puts it on the next one. `place()` cannot see this: it \
         scans bands of FLOATS, and the obstruction here is the line's own inline content. A \
         top-bound alone moved this row from right to WRONG, which is how the missing half was found",
    );
}
