#!/usr/bin/env python3
"""Turn `docs/loop/CADENCE.tsv` into `docs/loop/CADENCE.md` — the loop, measured.

**The row is not the point. The derivative is.**

A single tick's numbers say nothing. Forty of them answer the questions this project actually has and has
never been able to answer:

* how long does a tick really take, end to end — implement, debug, verify wall, land?
* how many ticks does one capability cost?
* is the verify wall getting slower (which taxes every future tick)?
* does near-horizon work move WPT at all? (Tick 64 says **no** — a 60x DOM speedup moved WPT by zero
  subtests, and that is worth knowing before planning the far horizon around it.)
* at the observed rate, how many ticks stand between here and parity?

The last question is the one to be careful with, and this file refuses to answer it with a straight line.
A linear extrapolation of WPT from a handful of points is a fabrication with a decimal point on it, and
this project's whole methodology is that a number you cannot defend is not a result. So the projection is
stated as a **rate over the measured window**, with its own sample size attached, and nothing more.
"""

import statistics
import sys
from pathlib import Path

TSV = Path("docs/loop/CADENCE.tsv")

# The far horizon, as the directive names it. It is deliberately NOT used to project a finish line: the
# rate we can measure comes from the `dom/` subset (6,418 subtests), and multiplying a subset's rate up to
# the whole suite is a category error dressed as arithmetic.
WPT_TOTAL_UNIVERSE = 50_000


def human_dt(sec: float) -> str:
    if sec <= 0:
        return "—"
    if sec < 90:
        return f"{sec:.0f}s"
    if sec < 5400:
        return f"{sec / 60:.0f}m"
    if sec < 172800:
        return f"{sec / 3600:.1f}h"
    return f"{sec / 86400:.1f}d"


def main() -> None:
    if not TSV.exists():
        print("# Cadence\n\nNo ticks recorded yet.")
        return

    rows = []
    with TSV.open() as f:
        header = f.readline().rstrip("\n").split("\t")
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < len(header):
                parts += [""] * (len(header) - len(parts))
            rows.append(dict(zip(header, parts)))

    def num(r, k, d=0.0):
        try:
            return float(r.get(k) or d)
        except ValueError:
            return d

    rows.sort(key=lambda r: int(r["tick"]))
    out = []
    w = out.append

    w("# The cadence — the loop, measured\n")
    w("*Generated by `scripts/cadence-report.py` from `docs/loop/CADENCE.tsv`. Appended mechanically by")
    w("`scripts/tick.sh` on every tick that lands. **Do not hand-edit.***\n")
    w("> We have spent seventy ticks measuring the browser and none measuring the loop. This is the loop:")
    w("> how fast it turns, what a tick costs, and what a tick buys — against the two horizons that")
    w("> define the project. **The row is not the point. The derivative is.**\n")

    # ── The clock.
    deltas = [num(r, "delta_s") for r in rows if num(r, "delta_s") > 0]
    walls = [num(r, "wall_s") for r in rows if num(r, "wall_s") > 0]
    recent = deltas[-10:] if len(deltas) >= 3 else deltas

    w("## Clock speed\n")
    w("| | value | over |")
    w("|---|---|---|")
    w(f"| ticks landed | **{len(rows)}** | ticks {rows[0]['tick']}–{rows[-1]['tick']} |")
    if deltas:
        w(f"| median tick cycle | **{human_dt(statistics.median(deltas))}** | {len(deltas)} intervals |")
        w(f"| median, last 10 | **{human_dt(statistics.median(recent))}** | {len(recent)} intervals |")
        w(f"| fastest / slowest | {human_dt(min(deltas))} / {human_dt(max(deltas))} | |")
        span_h = (num(rows[-1], "epoch") - num(rows[0], "epoch")) / 3600
        if span_h > 0:
            w(f"| **ticks per hour** | **{len(deltas) / span_h:.2f}** | {span_h:.1f}h elapsed |")
    if walls:
        w(f"| median verify wall | **{human_dt(statistics.median(walls))}** | {len(walls)} ticks |")
        if len(walls) >= 6:
            first, last = statistics.median(walls[:3]), statistics.median(walls[-3:])
            trend = "getting slower ⚠️" if last > first * 1.25 else "flat or improving ✅"
            w(f"| wall trend | {human_dt(first)} → {human_dt(last)} — {trend} | first 3 vs last 3 |")
    w("")
    w("The **cycle** is the real unit: implement → debug → verify wall → land. The wall is only part of")
    w("it, and a wall that grows taxes every future tick, so it is tracked separately from the whole.\n")

    # ── The two horizons.
    w("## The two horizons\n")
    cap = [r for r in rows if r.get("claims")]
    fresh = [r for r in rows if r.get("wpt_fresh") == "1" and r.get("wpt_pass")]

    w("### Near — the daily driver (doc / app / platform web)\n")
    if cap:
        f_, l_ = cap[0], cap[-1]
        w(f"* **capabilities asserted** (`G_CAPABILITY`): {int(num(f_,'claims'))} → **{int(num(l_,'claims'))}**")
        w(f"* **live gates**: {int(num(f_,'gates'))} → **{int(num(l_,'gates'))}**")
        w(f"* **✅ rows in the capability ledger**: {int(num(f_,'patterns_ok'))} → **{int(num(l_,'patterns_ok'))}**")
        w(f"* **Bar 0 — oracle hangs**: {int(num(l_,'hangs'))} of 265 sites")
    caps_ticks = [r for r in rows if r.get("shape") in ("capability", "pattern-class", "bar-0")]
    if caps_ticks and len(rows) > 1:
        w(f"\n**{len(caps_ticks)} of {len(rows)} ticks** ({100*len(caps_ticks)/len(rows):.0f}%) moved a")
        w("user-visible capability. The rest were instruments, infrastructure and corrections — and the")
        w("ledger says the corrections were not overhead: three of its top three priorities were phantoms,")
        w("and finding that out redirected everything after it.\n")

    w("### Far — WPT (50,000 tests)\n")
    if fresh:
        f_, l_ = fresh[0], fresh[-1]
        fp, ft = num(f_, "wpt_pass"), num(f_, "wpt_total")
        lp, lt = num(l_, "wpt_pass"), num(l_, "wpt_total")
        w(f"* measured **{len(fresh)}** times (a carried-forward number is never counted as a measurement)")
        if ft:
            w(f"* first, tick {f_['tick']}: **{fp:.0f}/{ft:.0f}** = {100*fp/ft:.1f}%")
        if lt and l_ is not f_:
            w(f"* latest, tick {l_['tick']}: **{lp:.0f}/{lt:.0f}** = {100*lp/lt:.1f}%")
        if lp != fp and len(fresh) > 1:
            dticks = int(l_["tick"]) - int(f_["tick"])
            rate = (lp - fp) / max(dticks, 1)
            w(f"* **rate over the measured window: {rate:+.1f} subtests / tick** ({dticks} ticks)")
            w("")
            w("> **What this rate is NOT.** It is measured on the `dom/` subset — **6,418 subtests** — and")
            w("> the far horizon is ~50,000 across *all* of WPT, **which this project has never run**.")
            w("> Multiplying a subset's rate up to the whole is not an extrapolation, it is a category")
            w("> error, and it would produce a confident number about a thing that was never measured. So")
            w("> the projection is not made. What the rate *does* say is stated below, and it is the")
            w("> important part.")
            w("")
            if rate < 1.0:
                w(f"> **At {rate:+.1f} subtests/tick, near-horizon work is not moving WPT.** Ticks"
                  f" {f_['tick']}–{l_['tick']} shipped a 60× DOM speedup, real prototypes, a canvas")
                w("> rasterizer, element scrolling, `display: contents` — **every one a genuine capability")
                w("> win for the daily driver — and WPT moved by a single subtest.** That is not a failure;")
                w("> it is a *measurement of the relationship between the two horizons*, and it says they")
                w("> are nearly orthogonal. **The far horizon will not arrive as a side-effect of the near")
                w("> one. It has to be spent on directly**, and the WPT horizon map")
                w("> (`docs/wiki/wpt-horizon.md`) is where those ticks get aimed.")
        else:
            w("* no change across the measured window")
    else:
        w("*No fresh WPT measurement recorded yet. `scripts/wpt-run.sh` writes one; a carried-forward")
        w("figure is marked and never counted as a measurement.*")
    w("")
    w("**Near-horizon work does not automatically move the far horizon**, and the log is what proves it:")
    w("tick 64 made DOM node creation **60× faster** and fixed prototype patching across the whole web")
    w("platform — and moved WPT by **zero subtests**, A/B'd on the same tree. Two horizons, two budgets.\n")

    # ── Cost of a capability.
    if caps_ticks and deltas:
        med = statistics.median(deltas)
        w("## What a capability costs\n")
        w(f"* **{len(caps_ticks)}** capability ticks, median cycle **{human_dt(med)}**")
        w(f"* median diff per tick: **+{statistics.median([num(r,'added') for r in rows]):.0f} / "
          f"−{statistics.median([num(r,'deleted') for r in rows]):.0f}** lines across "
          f"{statistics.median([num(r,'files') for r in rows]):.0f} files\n")

    # ── The ledger itself.
    w("## Every tick\n")
    w("| tick | landed | Δ | shape | wall | diff | gates | claims | WPT | what it was |")
    w("|---:|---|---:|---|---:|---|---:|---:|---|---|")
    for r in rows:
        d = num(r, "delta_s")
        wpt = ""
        if r.get("wpt_pass") and r.get("wpt_total"):
            pct = 100 * num(r, "wpt_pass") / max(num(r, "wpt_total"), 1)
            wpt = f"{pct:.1f}%" + ("" if r.get("wpt_fresh") == "1" else " ·")
        w(
            f"| **{r['tick']}** | {r['iso'][:16].replace('T',' ')} | {human_dt(d)} | {r['shape']} | "
            f"{human_dt(num(r,'wall_s'))} | +{int(num(r,'added'))}/−{int(num(r,'deleted'))} | "
            f"{int(num(r,'gates'))} | {int(num(r,'claims'))} | {wpt} | {r['headline'][:90]} |"
        )
    w("\n*`·` after a WPT figure means **carried forward**, not measured this tick.*")

    print("\n".join(out))


if __name__ == "__main__":
    sys.exit(main())
