#!/usr/bin/env bash
# Disk hygiene. Run at every EPOCH audit, and whenever /home crosses 85%.
#
# A full disk is a build failure that looks like a code failure — you lose an hour to a linker error
# that is really `ENOSPC`. The build tree grows without bound: `target/debug` alone reaches tens of
# gigabytes because every dependency, every test binary and every incremental fragment is kept
# forever, and almost none of it is ever read again.
#
# What is safe to delete, and why:
#   * `target/debug/incremental` — regenerated on the next build, costs one slower compile.
#   * `target/debug` — we gate and ship on RELEASE (the shipping configuration, ADR-011). The debug
#     tree exists for `cargo test`, which rebuilds what it needs.
#   * old banked binaries — the newest N are kept; the git tag preserves the source of every one.
#   * old oracle snapshots — regenerated by the next crawl.
#
# What is NEVER deleted: `target/release` (the gates and the banked builds come from it), the git
# repo, `.env`, the profile store.
set -uo pipefail
cd "$(dirname "$0")/.."

KEEP_BUILDS="${MANUK_BANK_KEEP:-6}"
BANK="$HOME/manuk-builds"

before=$(df -h /home | awk 'NR==2 {print $4}')
pct=$(df /home | awk 'NR==2 {gsub(/%/,""); print $5}')
echo "▶ /home is ${pct}% full ($before free)"

# Incremental fragments live in RAM now (METHODOLOGY 10.1) — flush them there, and reclaim any that
# a build made before the ramdisk was wired up. `rm -rf` through the symlink would delete the RAM
# contents and leave a live symlink, which is exactly what we want either way.
echo "  · incremental fragments (RAM-resident; flushed, not written to disk at all)"
./scripts/ramdisk.sh --flush >/dev/null 2>&1 || rm -rf target/debug/incremental target/release/incremental 2>/dev/null

# ── GRANULAR ORPHAN PRUNE (observer, tick 141) — the SYSTEMATIC, SAFE, FREQUENT reclaim that keeps target/
# bounded so the 95% full-purge (cold rebuild) below never fires. target/*/deps accumulates old-hash dep
# versions + stale test binaries that cargo never garbage-collects (73G observed). A file NOT read by ANY
# build in >1 day (access time; /home is relatime) is an ORPHAN — it is not in the current build's working
# set, so deleting it costs NO cold rebuild. In-use artifacts (every gate test bin, every dep the build
# links) are READ on every verify, so their atime stays fresh and they are KEPT. This is the opposite of the
# old `rm -rf target/debug`: it removes only what is provably unused, and it runs every time hygiene fires.
echo "  · target/*/deps orphans — files unread by any build in >1 day (not in the current build's set)"
find target/debug/deps target/release/deps -type f -atime +1 -delete 2>/dev/null

# ── ORPHAN TEST-BINARY PRUNE (observer, tick 147) — the atime prune above MISSES the biggest bloat: every
# engine change rebuilds the ~65 gate test binaries under a NEW fingerprint hash, orphaning the old-hash copy,
# and each mozjs-static bin is 350-560MB. ~150 accumulate = ~54G that `atime +1` never catches (all touched
# THIS session). Cargo never GCs them. Keep only the NEWEST-mtime executable per name-stem in deps/ (that IS
# the current gate bin the next verify links); delete older-hash duplicates. Provably-superseded orphans only,
# so it costs NO cold rebuild. Reclaimed ~40G/pass at tick 147 (debug 72G->36G, /home 91%->77%). Runs every
# fire, BEFORE the >=95% debug-purge below — so it frees the space first and the cold-purge stays a last resort.
echo "  · target/*/deps orphan test-binaries (old-hash duplicates; keep newest per name — the recurring bloat)"
for _d in target/debug/deps target/release/deps; do
  [ -d "$_d" ] || continue
  for _stem in $(find "$_d" -maxdepth 1 -type f -executable ! -name '*.*' -printf '%f\n' 2>/dev/null | sed -E 's/-[0-9a-f]{8,}$//' | sort -u); do
    find "$_d" -maxdepth 1 -type f -executable -name "${_stem}-*" ! -name '*.*' -printf '%T@ %p\n' 2>/dev/null \
      | sort -rn | tail -n +2 | cut -d' ' -f2- | xargs -r rm -f
  done
done

# GRANULAR DEBUG-TREE POLICY (observer, tick 119). The debug tree is NOT disposable: verify.sh's gates run
# `cargo test` in DEBUG, so `rm -rf target/debug` forces a full cold rebuild on the very NEXT verify. The
# disk oscillates at 84-91%, so the old `pct >= 85` rule fired almost every tick — turning a ~10min warm
# tick into a ~35min cold-rebuild + OOM-roulette, the exact thrash that stalled the loop. The 28G is mostly
# mozjs-linked test binaries (the warm cache) plus dep rlibs written once / read forever; regenerating it
# buys nothing. So PRESERVE the warm cache and reclaim the CHURN instead: incremental now lives in RAM
# (ramdisk, flushed above), and banked builds + oracle snapshots are pruned below. Nuke the whole debug
# tree only as an explicit LAST RESORT — `--aggressive`, or a critical >=95% where ENOSPC is imminent and
# one cold rebuild beats a failed build.
# ── STALE-PCT FIX (observer, tick 234). `pct` was read ONCE at the top, BEFORE the orphan-prune above
# frees ~34G in 3.5s. So a transient >=95% linking spike still fired this destructive purge even when the
# prune had already brought the disk back to ~75% — nuking the warm cache and forcing the ~35min cold
# rebuild this script exists to PREVENT. Re-measure so the purge only fires if we are STILL critical after
# reclaiming. This matters more now the cron runs every 3min (more chances to catch a transient spike).
pct=$(df /home | awk 'NR==2 {gsub(/%/,""); print $5}')
if [ "${1:-}" = "--aggressive" ] || [ "$pct" -ge 95 ]; then
  echo "  · target/debug — CRITICAL ${pct}% AFTER prune: full purge to avert ENOSPC (a cold rebuild follows)"
  rm -rf target/debug 2>/dev/null
else
  echo "  · target/debug preserved (warm cache kept; only regenerable churn reclaimed — incremental is in RAM)"
fi

echo "  · banked builds beyond the newest $KEEP_BUILDS (git tags keep the source of every one)"
if [ -d "$BANK" ]; then
  ls -1t "$BANK"/manuk-*-* 2>/dev/null | grep -v '\.md$' | tail -n +$((KEEP_BUILDS + 1)) | while read -r old; do
    rm -f "$old" "$old.md"
    echo "      pruned $(basename "$old")"
  done
fi

echo "  · oracle snapshots older than 7 days (the next crawl refetches)"
find /tmp/manuk-oracle-snapshots -type f -mtime +7 -delete 2>/dev/null
find /tmp -maxdepth 1 -name 'manuk-*.html' -mtime +1 -delete 2>/dev/null

after=$(df -h /home | awk 'NR==2 {print $4}')
echo "▶ now $after free (was $before)"
