#!/usr/bin/env bash
# Disk hygiene. Run at every EPOCH audit, and whenever /home crosses 85%.
#
# A full disk is a build failure that looks like a code failure — you lose an hour to a linker error
# that is really `ENOSPC`. The build tree grows without bound: `target/debug` alone reaches tens of
# gigabytes because every dependency, every test binary and every incremental fragment is kept
# forever, and almost none of it is ever read again.
#
# What is safe to delete, and why:
#   * `target/debug/incremental` — regenerated on the next build, costs one slower compile.
#   * `target/debug` — we gate and ship on RELEASE (the shipping configuration, ADR-011). The debug
#     tree exists for `cargo test`, which rebuilds what it needs.
#   * old banked binaries — the newest N are kept; the git tag preserves the source of every one.
#   * old oracle snapshots — regenerated by the next crawl.
#
# What is NEVER deleted: `target/release` (the gates and the banked builds come from it), the git
# repo, `.env`, the profile store.
set -uo pipefail
cd "$(dirname "$0")/.."

KEEP_BUILDS="${MANUK_BANK_KEEP:-6}"
BANK="$HOME/manuk-builds"

before=$(df -h /home | awk 'NR==2 {print $4}')
pct=$(df /home | awk 'NR==2 {gsub(/%/,""); print $5}')
echo "▶ /home is ${pct}% full ($before free)"

echo "  · incremental fragments"
rm -rf target/debug/incremental target/release/incremental 2>/dev/null

# The debug tree is the hog and the least valuable: nothing ships from it and nothing gates on it.
if [ "${1:-}" = "--aggressive" ] || [ "$pct" -ge 85 ]; then
  echo "  · target/debug (rebuilt on demand; we gate and ship on release)"
  rm -rf target/debug 2>/dev/null
fi

echo "  · banked builds beyond the newest $KEEP_BUILDS (git tags keep the source of every one)"
if [ -d "$BANK" ]; then
  ls -1t "$BANK"/manuk-*-* 2>/dev/null | grep -v '\.md$' | tail -n +$((KEEP_BUILDS + 1)) | while read -r old; do
    rm -f "$old" "$old.md"
    echo "      pruned $(basename "$old")"
  done
fi

echo "  · oracle snapshots older than 7 days (the next crawl refetches)"
find /tmp/manuk-oracle-snapshots -type f -mtime +7 -delete 2>/dev/null
find /tmp -maxdepth 1 -name 'manuk-*.html' -mtime +1 -delete 2>/dev/null

after=$(df -h /home | awk 'NR==2 {print $4}')
echo "▶ now $after free (was $before)"
