#!/usr/bin/env bash
# ── LEVER BOARD — the biggest-impact-first work list + progress tally. The observer owns this; the agent
# CONSULTS it to pick the next tick so it attacks the broadest-impact mechanism first, not a narrow win.
#
# Ranks reachable areas by FAILING subtests, split by FLIP-RATE class: HIGH-FLIP areas (DOM/CSSOM/API/
# selector/parsing surfaces) yield many green subtests per fix; LAYOUT areas (flex/grid/sizing/…) are a
# multi-assertion slog (one fix flips ~nothing) — big in raw count but low yield. Exhaust high-flip mass
# FIRST. The encoding tail is out of v1 scope (V1-SCOPE.md) and excluded from the reachable tally.
#   usage: scripts/lever-board.sh
set -uo pipefail
cd "$(dirname "$0")/.."
A=docs/loop/WPT-AREAS.tsv
B=$'\033[1m'; C=$'\033[36m'; G=$'\033[32m'; Y=$'\033[33m'; O=$'\033[0m'
TARGET=83   # daily-driver MVP DIAGNOSTIC: reachable (non-tail) pass-rate goal. Real bar = real-site drivability.

# ── WORKFLOW WARNING (observer, tick 134). This has HUNG the loop 3× and needed a manual kill each time:
R=$'\033[31m'
printf "%s⚠ NEVER poll with a pgrep-of-your-own-pattern wait loop%s — e.g. \`while pgrep -f \"cargo test X\"; do sleep; done\`\n" "$R$B" "$O"
printf "  or \`until ! pgrep -f \"scripts/tick.sh\"; do ...; done\`. The pattern string is in the WAIT LOOP'S OWN cmdline, so\n"
printf "  pgrep always matches itself, never returns empty, and the loop spins FOREVER even after the real job finished.\n"
printf "  Instead: run cargo/tick.sh/tests in the FOREGROUND and let them block. If the harness backgrounds a long command,\n"
printf "  wait on its OUTPUT-FILE CONTENT (e.g. \`grep -q 'VERIFY:' out\`), never on pgrep of a string your wait command contains.\n\n"

# ── PHASE MANDATE (observer, tick 138+) — DAILY-DRIVER CAPABILITY via a FIXED SEQUENCE. ENFORCED. Full roadmap +
# good-enough bars + agentic fallbacks: docs/wiki/lever-map.md. Agent picks the LOWEST-NUMBERED unmet target.
printf "%s🎯 PHASE MANDATE — pick the LOWEST-NUMBERED unmet target below. Falsifiable bar, NOT WPT%%.%s\n" "$R$B" "$O"
printf "  %s\U0001F6A8 FIRST ACTION THIS SESSION (observer 2026-07-29, USER DIRECTIVE): run a FULL corpus fidelity sweep and BANK docs/loop/SWEEP-t<TICK>-rows.tsv BEFORE any capability tick%s — shape has been UNMEASURED for 30+ ticks and the loop is blind on its own headline. Use the SAME path that produced SWEEP-t706-rows.tsv (the manuk-wpt fidelity sweep over the full corpus + oracle-merge). It is OFF the per-tick wall; run it as YOUR OWN process (the observer must NOT run it — cross-process contention false-REDs the perf gates). Then scripts/fidelity-progress.sh records the row and prints the burndown slope vs t706 (in-scope pass 5.3%%, need +188). AFTER the sweep lands, proceed to the ranked SHAPE burndown in the CO-#1 block below.%s\n" "$R$B" "$O" "$O"
printf "  %s\U0001F9F1 CO-#1 UPDATE (observer 2026-07-29 / USER DIRECTIVE — the FINITE path to render-done; SUPERSEDES the MISSING_BOX-FIRST ordering + stale numbers in the t684/t685/t686 blocks below)%s. The render metric is now WINNABLE + HONEST: shape>=0.75 over the IN-SCOPE corpus (bot-walls EXCLUDED + watched per cert §3, NOT counted as fails — dividing by all 265 capped the ceiling at 80%% and made 95%% impossible). %sHonest baseline t706: 11/209 = 5.3%%, target 199, need +188%s. Full plan: %sdocs/loop/PHASE0-RENDER-BURNDOWN.md%s. THREE cuts prove the gap is CONCENTRATED (finite), not a CSS death-tail: the 11 sites we already PASS are exactly the trivial single-column text pages (danluu/lite.cnn/arxiv); 61%% of FAILING sites have coverage>=0.95 (every box drawn, only WRONG position); shape is a dy term — one wrong height cascades down the whole subtree, so 14002 <div> hits are a HANDFUL of mechanisms, not 14002 bugs. %sORDER CORRECTED: SHAPE/POSITION FIRST, not missing-box-first%s — coverage is already ~86%% mean; the binding gap is composed block/flex layout math on FULLY-COVERED pages. IMMEDIATE: %s(1) RUN A FRESH FULL SWEEP NOW%s — 30+ ticks landed since t706 with shape UNMEASURED, the loop is blind on its own headline (agent runs it; observer NEVER does — contention false-REDs perf gates). %s(2) MECHANISM ORACLE — NEARLY FREE%s: oracle::cluster (tests/wpt/src/oracle.rs:344-377) ALREADY computes the {displaced|mis-sized}:{width|height|y|x} ~Npx signature; run_oracle_merge (main.rs:2649-2654) DISCARDS it back to geometry:<tag> before writing CLUSTERS.md. STOP discarding it -> work ranks by PRIMITIVE not tag. KEY INSIGHT (layout analysis): container-WIDTH errors LAUNDER into dy (a box a few px too wide re-wraps its prose -> wrong line count -> whole-line height cascade), invisible as a width bug — so h_overflow (ALREADY in the sweep TSV: wikipedia 52, apple 127) is the ready proxy; rank on it first. ALREADY CHROME-CORRECT, do NOT re-grind: margin-collapse / line-height:normal / half-leading+strut / default UA margins / default font / scrollbar (verified file:line). %s(3) RANKED BURNDOWN%s: ONE primitive per tick, ranked by (in-scope sites × dy severity), verified on the anchor sites %snews.ycombinator 0.72 / a11yproject 0.44 / wikipedia 0.52 / blog.rust-lang 0.63 / martinfowler 0.58 / whatwg 0.51%s (fully-covered, no confound) — a fix MUST raise in-scope-pass on the next sweep or it is reverted/re-scoped. fidelity-progress.sh now prints +X pts/sweep -> ~N sweeps to 95%% (the finiteness readout). Function-axis capability ticks stay welcome, but RENDER is the binding constraint until in-scope-pass clears ~50%%.%s\n" "$R$B" "$O" "$Y$B" "$O" "$C$B" "$O" "$R$B" "$O" "$G$B" "$O" "$G$B" "$O" "$G$B" "$O" "$C$B" "$O" "$O"
printf "  %s\U0001F9F1 CO-#1 = THE RENDERING GAP -> 95%% (observer t684 / 2026-07-27 — USER DIRECTIVE; SUPERSEDES blocks below on conflict)%s. DRIVE COVERAGE/SHAPE TO THE 95%% BAR. The last ~20 ticks were floor-gates (window.<id>, reportError) + instrument-hardening — real work, but they do NOT move the bar: coverage sat ~4.7%% / shape ~48%% FLAT while GATES climbed +9/day. THE GAP IS ALREADY MAPPED: %sdocs/loop/CLUSTERS.md IS the priority ledger%s (the oracle's own ranking by DISTINCT SITES). Attack it TOP-DOWN, ONE shared ROOT CAUSE per tick, and PROVE the cluster's site-count SHRINKS next sweep. Mechanism mass: %sMISSING_BOX 401 sites / 17154 hits (Chrome renders it, we render NOTHING -> kills COVERAGE)%s; geometry 1781 / 37184 (box present, WRONG position -> kills SHAPE); display 423 / 5945 (wrong computed display). ORDER: (1) MISSING_BOX FIRST — a dropped box displaces its whole subtree and tanks coverage hardest; top C3833 <div> 7544/32, C0a9e <span> 2052/19, Ccd7f <path> 1658/34 — find WHY we emit no box where Chrome does (display-compute? an unsupported property dropping the element? anon/whitespace box?). (2) geometry NEAR-MISS — tick-267 still holds: ONE shared constant (font-metrics / line-height / margin / border-box rounding) likely snaps MANY boxes into 8px tolerance at once; top C01ca <div> 14002/111. (3) display-map fixes. %sRULE: a tick is ON-MANDATE ONLY if it NAMES a cluster it shrinks%s — floor-gates + instrument-polish are NO LONGER CO-#1 (take one only when a cluster is genuinely blocked); a perf tick counts ONLY if tied to a MISSING_BOX cluster (slow load -> incomplete paint -> dropped box). Re-run the sweep each cycle, bank the cluster mass, watch it fall.%s\n" "$R$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$O"
printf "  %s\U0001F517 REFINEMENT (observer t685 — VALIDATED BY MOVEMENT: credits perf, sharpens on SHAPE)%s: coverage 4.7%% -> 6.5%% (missing 102->100, a concrete box count) CONFIRMS perf-is-a-fidelity-input — timing-caused missing boxes ARE a real MISSING_BOX cause, so %sa perf/load-budget tick that MOVES COVERAGE is ON-MANDATE%s (the t684 hard demotion of perf was too harsh; do not stop it while coverage climbs). BUT coverage is only HALF the bar. %sSHAPE ~48%% vs 95%% is driven by GEOMETRY (font-metrics / line-height / margin / border-box rounding), which PERF CANNOT FIX%s — a mis-placed box is layout math, not paint timing. The geometry NEAR-MISS lever (C01ca div 14002/111; tick-267: ONE shared constant snaps MANY boxes into 8px at once) is the HIGHEST-YIELD SHAPE lever and is UNTOUCHED after 2 post-steer ticks (both perf/measurement). %sSO: perf stays on-mandate WHILE coverage climbs, but at least every OTHER tick must attack a GEOMETRY or display cluster to move SHAPE%s — coverage alone cannot clear 95%%, and no perf tick ever will. Next non-perf tick = the geometry near-miss shared constant (C01ca).%s\n" "$G$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$O"
printf "  %s\U0001F4C8 KEEP ALL FOUR CLIMBING TO 95 — TRACKED (observer t686, user directive)%s: the four Phase-0 fidelity numbers must MONOTONE-climb and are now recorded every sweep in %sdocs/loop/FIDELITY-PROGRESS.tsv%s (scripts/fidelity-progress.sh; ops-check alerts on staleness / scorability-regression / the DENOMINATOR TRAP). Baseline (full 265-site corpus): %sscorable 106/265 · cov_pooled 84.8%% · placement/shape 6.4%% · visual 53.5%%%s. ⚠ THE FULL CORPUS SWEEP IS STALE (7d at t686) — the recent 4.7->6.5 coverage movement is only the HEAD-20 subset; the corpus-wide trend is BLIND until the full sweep re-runs. %sSO, every few ticks: RE-RUN the full sweep (manuk-wpt fidelity over the corpus) so the ledger trend stays live%s. Drive each number and beware the traps: SCORABILITY up = more sites measurable (NOT by dropping hard ones); COVERAGE up = boxes rendered (but a hard site scoring can LOWER mean — read cov_pooled + the ledger, not one %%); PLACEMENT/SHAPE up = geometry near-miss (the 6.4%% is the worst number and needs the shared-constant fix); VISUAL up = paint correctness. A number that rose while scorable FELL is composition, not progress.%s\n" "$G$B" "$O" "$C$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$G$B" "$O" "$O"
printf "  %s\U0001F3AF PHASE 0 = THE FULL DAILY-DRIVER CHECKLIST, not the 5 finish-line levers (CORRECTED, tick 222). Those 5 (streaming/a11y-states/WebSocket/scroll-anchor/forced-reflow) were a MILESTONE. Phase 0 is COMPLETE ONLY WHEN THE BROWSER WORKS ON ~ALMOST EVERY WEBSITE across ALL classes (doc/app+hydration/social-feeds/platform-realtime/MEDIA) — tracked by scripts/phase0-progress.sh (now ~44%%: doc 44 / app 64 / platform 30 / MEDIA 5 / cross 48) — until every CRITICAL/reachable edge is works|gated and only the honest OUT-OF-REACH set (canvas office-suites, heavy-WebGL, DRM) is unmet. GRIND THE FULL CHECKLIST (constellation --gaps + DAILY-DRIVER-EDGES.md). STALE-LIST SUPERSEDED (observer t642): this tick-222 TOP-REMAINING list is HISTORICAL — media / IndexedDB / canvas-fillText / completeness / clipboard all landed. The AUTHORITY is the CERTIFICATION REDESIGN + STEP-2 blocks below. THE REAL binding Phase-0 constraint is FIDELITY: shape ~40%% vs the 95%% bar on the first complete bounded certificate. Do NOT pick media/codec ticks — that arc is DONE (t264); pick the placement-fidelity root-cause the sweep surfaces. DO NOT declare Phase 0 done or trigger Phase 1 until the certificate holds.%s\n" "$C$B" "$O"
printf "  %s\U0001F52C CERTIFICATION REDESIGN (observer, tick ~581 / 2026-07-25 — SUPERSEDES the tick-543 exit-verification orders below where they conflict)%s. The recent episode proved the fidelity RIG can flatter itself (six false numbers in one session) and that the 265-site corpus is a convenience sample with timeouts dropped, so 'near-done' was really 'further than thought'. THE AUTHORITY IS NOW docs/loop/DAILY-DRIVER-CERTIFICATION.md — read it. %sNEW CO-#1, in strict order (each a verify-gated tick; the fidelity instrument in manuk-wpt is agent-territory, scripts/ stay observer-owned):%s (1) FALSIFY THE CERTIFICATE FIRST — extend the falsify pass to the fidelity cert: deliberately break each term (disable flexbox; make IndexedDB throw; nudge a box 30px) and PROVE that term goes RED. No cert term is trusted until proven falsifiable; this prevents the recurring self-delusion and is the top priority. (2) ADOPT docs/bench/corpus-v2.tsv (400 representative CrUX-sampled sites, HEAD traffic-weighted + TAIL uniform strata) as the certification corpus, TIERED: a small fixed-seed sub-slice in the per-tick wall as a real-site regression guard + the full sweep off-tick. FIXED DENOMINATOR — a timeout/crash/bot-wall is a COUNTED FAIL/EXCLUDED with a reason, NEVER a silent drop (dropping the hard sites is what made every past reading optimistic). (3) COMPOSE FUNCTION into the certificate — the on-page probe records which capabilities each site TOUCHES; require those green PER-SITE via BiDi, starting with the throw-class killers (IndexedDB, the observer trio). daily-driver-pass(site) = renders AND functions. (4) RECONCILIATION GATE — sampled==scored+FAIL+EXCLUDED and parsed==probed==scored; any imbalance is an instrument bug, not a result. %sMeanwhile the current cascade/layout/text render-fidelity fixes REMAIN VALID — they move Layer C-render of the new cert; do NOT stop them.%s\n" "$G$B" "$O" "$R$B" "$O" "$Y$B" "$O"
printf "  %s\U0001F9F9 BOARD CLARITY (observer t599, per your surface audit #33 — 'the board steers at finished work')%s: most CO-#1 letter-blocks below are FINISHED — media (A), OAuth (B), canvas fillText (C) are all DONE. The ONLY live CO-#1 priorities are: (1) the CERTIFICATION REDESIGN block below — RUN the corpus-v2 PILOT for the first honest render×function number; (2) probing the genuinely-open (D) unknowns; (3) MAP HONESTY (observer t601) — run scripts/map-reconcile.sh and drive its 26 drift rows to 0 (cite the REAL backing gate, or set status=missing/unmeasured), so no capability is claimed without a gate that EXISTS; observer then wires --strict into the wall. The deadest historical blocks (t235/t267/t328) were pruned t601; the remaining tick-223/232/264/543 blocks below stay as context only, full history in git.%s\n" "$G$B" "$O" "$O"
printf "  %s\U0001F4CF STEP-2 REMINDER (observer, tick ~592)%s: the cert machinery is built (falsify + fixed-denominator-as-type + function-leg/producer, t583-591) and you are productively fixing cert-surfaced + render-fidelity gaps — good, but the REMAINING VALUE of the redesign is the MEASUREMENT, and it must not slip behind more capability fixes. NEXT (POST-PILOT, observer t602): the PILOT RAN (commit 2a085555) — the FIRST honest number on the representative corpus is 0 of 5 scored sites passing, MEAN VISUAL 63.4%% / MEAN SHAPE 48.2%% vs a 95%% bar (a NEW baseline, NOT differenceable against the old convenience corpus). The DENOMINATOR works as designed: 6 fetch-fails + 9 unscored of 20 count AGAINST the bar, and the instrument self-flagged imdb as unmeasurable rather than pass it. Do NOT jump to the full 400-site sweep — p-hat (0/5) cannot size it; the binding constraint is the 64%% unscored/failed rate. TWO next targets, both MEASURABILITY: (1) fix WHY 9 of 14 cannot be scored; (2) the pilot's unrequested finding — we are SLOW on real HEAD sites (10 of 14 tripped OURS-IS-SLOW; welt.de 34.4s vs Chrome 6.7s), the 12s load budget is exhausted so pages paint incomplete and shape is PARTLY a TIMING result. Perf is now a fidelity INPUT, not a comfort metric. THIS number is the real Phase-0 distance.%s\n" "$C$B" "$O" "$O"
printf "  %s\U0001F3C1 CURRENT ORDERS (observer, tick ~543 / 2026-07-24 — SUPERSEDES every steer below where they conflict)%s. The capability count FEELS near-done, but the Phase-0 CERTIFICATE has NOT been measured with the rebuilt instrument — the last real jarring numbers are the t380->t392 sweep, STALE by ~150 ticks + the whole instrument rebuild (t531-537). Feeling done is not being done; that is exactly what the instrument exists to catch. %sSTEP 1 — RUN THE EXIT VERIFICATION NOW (Tier-3, top priority, ~5-10 ticks)%s: (a) a FRESH full-corpus sweep with the rebuilt G1 instrument (SHAPE + selector-path keying + all four jarring invariants, bricks t531-537) — append one actuals line to PHASE0-ROADMAP-ANCHOR.md; (b) run test262 (SpiderMonkey embedded, near-zero cost, number unknown); (c) run the 100-tab RSS benchmark. This converts near-done into a NUMBER and tells us the real distance to the certificate. %sSTEP 2 — FINISH THE IN-SCOPE BOUNDED REMAINDER (everything in PHASE0-BOUNDED-REMAINDER.md Tier-1/Tier-2 that is NOT the death-tail), re-probing each first (rows run stale-PESSIMISTIC)%s: password vault + autofill (crypto core done in store/lib.rs, the iceberg is UX), live CSS transition/animation timeline (end-state-only today), the visual-effects bundle (filter / backdrop-filter / mix-blend-mode / clip-path / background-attachment), form-widget painting (date/color/time pickers, native select popup, accent-color), cookie-attribute enforcement, bidi full line reordering, WebAuthn full round-trip, codec-breadth completion, multicol, print output — plus ANYTHING the fresh sweep flags as jarring. %sDEATH-TAIL — do NOT build; feature-detect cleanly and NAME as post-Phase-0 exceptions%s: the 16-item cut line (Widevine/WebRTC/WebTransport-HTTP3/SharedWorker/canvas-office EDITING/in-browser-PDF/devtools/process-per-tab/Web-Audio/push) PLUS subgrid, @scope, anchor-positioning, JPEG XL, WebCodecs, scroll-driven animations, custom highlights, text-wrap:balance, JSPI, scoped registries. %sBORDERLINE (build ONLY if the fresh sweep proves a real site-class is jarring without it, else defer post-Phase-0)%s: WebGL software backend (raster fallback exists — the designated down-scope valve) and MathML. %sSTEP 3 — HOLD%s: Phase-0 EXIT = the FIDELITY-SCORING-REDESIGN.md certificate MET on the rebuilt instrument (Bar-0 + jarring invariants >=95%% + shape >=0.75 on >=95%% + interactivity >=95%% + named exceptions only). Do NOT self-declare Phase 0 or trigger the Phase-1 cascade — when the certificate holds, JOURNAL it and STOP for explicit user go (dogfood pass pending). The tractable-tail instinct is the Presto death-tail in disguise; the value past the certificate is Phase 1, not more CSS.%s\n" "$G$B" "$O" "$R$B" "$O" "$C$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$O"
printf "  %s\U0001F9ED ANCHOR (observer, tick 461)%s: %sdocs/loop/PHASE0-ROADMAP-ANCHOR.md is the VERIFIED bound — ~85-150 ticks to the Phase-0 certificate from t460%s. Track against its remaining ledger: rich-editing subsystem (IN PROGRESS, 10-20), then WebAuthn/vault/bidi/animations/widgets/effects/MathML/multicol/print/ch-ex, ledger-driven jarring fixes toward the >=95%%-clean bar, exit verification (test262 / 100-tab RSS / repeat sweeps). RULES: append one actuals line to the anchor after EVERY full corpus sweep; the reading-order invariant has a TWO-SWEEP decision gate (cluster count must shrink >=30%%/cycle or re-derive cause-vs-instrument); WebGL is the down-scope valve if the total tracks high. The bound is falsifiable — report drift, never rationalize it.%s\n" "$G$B" "$O" "$C$B" "$O" "$O"
printf "  %s\U0001F6A8 HOT (observer, 18:40) — THE WALL IS UNIFIED ON ONE FEATURE SET (commit c059370)%s: verify.sh now builds/runs EVERY manuk-page gate incl. js_conformance and g_alloc under %sstylo,spidermonkey ONLY%s. Do NOT prewarm or build %s--features spidermonkey%s (no stylo) test binaries — that second variant is DEAD, its ~33G of binaries were reaped, and rebuilding it wastes ~10min + 33G for artifacts nothing will ever run. Prewarm = %scargo test --no-run -q -p manuk-page --features stylo,spidermonkey%s + the release workspace, nothing else. ALSO: STATUS banked a 706s wall from the CONTENDED tick-325 landing cycle (observer probes + hygiene ran beside it — a poisoned number, not a regression); the re-baselined mark is 189 (ceiling 245): ONE warm verify on the quiet box re-banks honestly (68s was measured at 17:49) — re-run, don't park.%s\n" "$R$B" "$O" "$G$B" "$O" "$R$B" "$O" "$C$B" "$O" "$O"
printf "  %s🔬 TAKE FID-SWEEP FIRST (observer, tick 233) — THE BIGGEST UNKNOWN IN THE PROJECT, and it is CHEAP because the pieces already exist. TODAY the G1 fidelity gate runs TWO static doc pages (news.ycombinator.com + a Wikipedia article) and scores 75.8%% visual / 100%% coverage. But docs/bench/oracle-corpus.txt holds 281 CATEGORY-STRATIFIED sites and its own header warns that a tiny corpus is an ANECDOTE: 'the bugs we had NOT found were exactly the ones no corpus site happened to use'. So 75.8%% on our EASIEST class tells us nothing about app/social/platform sites — and capability%% CANNOT see feature-present-but-site-broken. Grinding media to 100%% while blind to app-class fidelity is optimizing the metric we can see. %s⚠ CRITICAL DESIGN CONSTRAINT: do NOT wire 281 sites into verify.sh%s — each site is a render + Chrome compare; that would blow the WALL ratchet and brick every tick. Build a SEPARATE sweep (e.g. scripts/fidelity-sweep.sh) that runs the broad corpus OFF the per-tick path, writes a per-CATEGORY score table, and BANKS a headline number into RATCHET.tsv (there is currently NO fidelity mark there). Keep the per-tick G1 gate small and fast (2-5 sites) exactly as it is. DELIVERABLE: a category-stratified fidelity table (doc/app/social/platform/media) so we learn whether app-class sites actually WORK. That number redirects everything downstream and may show we are closer OR much further than 52%% capability suggests.%s\n" "$Y$B" "$R$B" "$O" "$O"
printf "  %s▶ CO-#2 SEAMS + MEASUREMENT [named, NOT letter-coded: M1-M7 below are MEDIA steps and must never be confused with these] (observer, tick 232 — from ENGINEERING.MD; full synthesis: docs/ENGINEERING-SYNTHESIS.md). Track C (CO-#1 above) stays the MAIN LINE and is unchanged. These INTERLEAVE: take ONE when a CO-#1 lever is blocked, stalled, or crash-gated. RATIONALE: these are SEAMS that are cheap NOW and cost MULTIPLES to retrofit, plus MEASUREMENT that redirects everything else. %sSEAM-JSENGINE%s — extract a trait boundary around mozjs (realms, GC handles, host hooks, module loading, microtask queue); ONE impl (mozjs); do NOT write a second engine. Gate: every JS call site routes through the trait, all JS gates still pass. HIGHEST-REGRET DEFERRAL IN THE REPORT. %sSEAM-TAINT%s — mark content-originated DOM strings TAINTED; add a task-scoped capability-token type. INERT at first: the BOUNDARY is the deliverable, enforcement is Phase 2. Prompt injection is unsolvable at the model layer, so it must be structural. %sSEAM-NOPIXELS%s — a flag in the paint path: layout + a11y tree, paint ELIDED. Gate: an agent tab yields a correct a11y tree with ZERO display items. Saves the whole raster+GPU+composite budget per background tab. %sSEAM-NODEID%s — GATE that node identity survives re-render/hydration; publish the contract (kills the #1 source of agent flakiness). %sMEM-HARNESS%s — RSS+PSS via /proc/PID/smaps_rollup, Tranco top-100 category-stratified, hold at 10/50/100 tabs, report median+p90 per-tab RSS. THIS CAN FALSIFY OUR OWN POSITIONING (within 20%% of Chrome = drop the memory claim) — that is the point; measure before marketing. %sTRI-ORACLE%s — add Firefox as a 2nd reference; flag ONLY diffs where Manuk disagrees with BOTH (Chromium-only diffing overfits to Chromium bugs). %sFID-SWEEP%s — wire structural fidelity to the REAL Phase-0 exit rule: >=0.75 on >=95%% of top-1000 + >=0.70 per top-20 category. The 128-cap checklist is the INPUT; this is the GATE.%s\n" "$Y$B" "$R$B" "$O" "$R$B" "$O" "$C$B" "$O" "$C$B" "$O" "$G$B" "$O" "$G$B" "$O" "$G$B" "$O" "$O"
printf "  %s\U0001FA7A RUN scripts/agent-doctor.sh IF ANYTHING FEELS STUCK (observer, tick 235)%s — it answers the one question liveness checks miss: %sis work LANDING?%s It probes tick-cadence stall, GATE ARITHMETIC (whether the ratchet mark makes landing mathematically impossible — the exact thing that silently ate tick 235 for 3h while every health signal read green), command-repetition loop signatures, verify-retry loops, staged-work stagnation, parked wip/ branches, and observer contention. %sTWO THINGS WAITING FOR YOU RIGHT NOW%s: (1) the pruner/wall race is FIXED for real this time — the stem prune is no longer skipped, it is now restricted to duplicates OLDER THAN THE RUNNING BUILD's start time, so it keeps reclaiming (31G in one live pass) while never touching your working set. Re-run the wall; it should come in warm. (2) %sYour tick-235 work is parked on branch wip/tick235-media-m4%s — you saved it correctly rather than lose it, and you were right to use --no-verify there to avoid committing my in-flight scripts/ edits. Once ONE verify lands under the 93s ceiling and status-update.sh banks it, cherry-pick that branch and land it. Do not redo the work.%s\n" "$C$B" "$O" "$Y$B" "$O" "$G$B" "$O" "$G$B" "$O" "$O"
printf "  %s\U0001F4CF PLACEMENT IS THE PHASE-0 GAP — FIRST REAL SWEEP DATA (observer, tick 267)%s. 33 stratified sites measured: %scov(ok) 85.9%% but PLACE(ok) 4.5%%%s against a >=75%% exit bar. We render nearly every element Chrome does and put almost none of them within 8px. Capability%% (62%%) CANNOT see this — every one of those features is present and gated. %sIt decomposes into THREE populations, and they need DIFFERENT fixes — do not treat 4.5%% as one bug:%s %s(1) NEAR-MISS (most tractable, do FIRST)%s: old.reddit mdy=12, airbnb mdy=20, wikipedia mdy=45, microsoft mdx=738/mdy=23 — offsets just past the 8px tolerance. A single shared root cause (default font metrics/line-height, a header or margin constant, border-box rounding) likely snaps MANY elements into tolerance at once. Highest yield per tick in the whole project right now. %s(2) MEDIAN-PERFECT, TAIL-BROKEN%s: youtube mdx=0 mdy=0 yet place=14.3%%; usa.gov mdx=0 mdy=82. The median element is EXACT, so the engine is not globally shifted — specific subtrees are. Use FIRST DIVERGENCE (now captured per site) to find which container starts the drift. %s(3) PAGE-HEIGHT COLLAPSE (NOT layout math)%s: apple mdy=5499, stripe mdy=6822, github mdy=1414. An offset of 6822px is not a layout error — it is CONTENT THAT NEVER RENDERED (lazy-load/IntersectionObserver/JS-driven expansion), so our page is drastically shorter and everything below shifts. Diagnose as a CONTENT problem, not a geometry one. %s⚠ INSTRUMENT CAVEAT: 39%% of sites are UNMEASURABLE%s (9 LOW_SAMPLE + 4 NO_IDS) — the id-based probe cannot score modern React/Tailwind pages, so 4.5%% is computed over 14 sites, not 33. %sRe-keying the structural probe off a stable selector-path (tag+class+nth-child) instead of [id] is now the gating fix FOR THE GATE ITSELF%s — without it we cannot honestly measure Phase-0 exit. Full rows: .git/fidelity-sweep/results.tsv (mdx/mdy/first_divergence per site).%s\n" "$R$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$G$B" "$O" "$C$B" "$O" "$C$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$O"
printf "  %s\u26A1 WALL 911s IS MINE AND SELF-CLEARING — DO NOT DEBUG IT (observer, tick 265)%s. I set `debug = 1` in the root Cargo.toml profile to stop /home hitting ENOSPC (93%% full; 78G of test binaries, 175MB of DWARF each). That invalidated every fingerprint, so ONE full rebuild ran and its 911s got banked as a green receipt — which is why the ratchet refuses right now. %sThe cache is already warm again (workspace build 0.44s, gate bin 0.36s, verified twice)%s, so your NEXT verify comes in near 64s, status-update banks it, and the block lifts by itself. Binaries went 552MB -> 350MB and disk 93%% -> 81%%. %sSo: just run your tick normally. Do NOT hunt the wall, do NOT touch Cargo.toml, do NOT re-derive this.%s If a verify comes back >200s on a WARM tree, THAT is new and worth reporting (use the twice-test: run the same cargo command twice — if the 2nd is not instant, something is deleting the working set). %sAlso: I am running FID-SWEEP myself right now%s (60 stratified sites, --jobs 1, off the tick path) so you do NOT need to — it is the Phase-0 exit gate and it had never been run. I will bank the headline. Take the NEXT item on the pivot list instead: %sIndexedDB (borrow redb/heed), then Service Worker + Cache API, container queries, AVIF%s.%s\n" "$Y$B" "$O" "$G$B" "$O" "$R$B" "$O" "$C$B" "$O" "$G$B" "$O" "$O"
printf "  %s\u2705 WALL-vs-HYGIENE RACE — FIXED, STOP RE-DIAGNOSING IT (observer, tick 235)%s: your memory `wall-vs-hygiene-cron-race` was CORRECT and the bug was MINE. I tightened the disk-hygiene cron to */3 while a verify wall runs 8-13min, so it pruned 3-4x MID-WALL and deleted the test binaries + release manuk-wpt that verify was about to run — hence sub-second cargo commands but a 480-800s aggregate against a 93s ceiling. %sFIXED in scripts/disk-hygiene.sh: the deps prunes are SKIPPED whenever rustc/cargo is live%s (safety valve: they still run if free disk <=25G, since ENOSPC beats a slow wall). Verified live — with 8 rustc running it prints \"deps prune SKIPPED\". ACTIVE ALREADY; cron execs from disk, no commit needed. %sSo just RE-RUN THE WALL.%s It should fall back toward the warm 50-70s range. Do NOT spend more ticks on cargo timing measurements, headless-gate feature thrash, or re-deriving the cause — that ground is covered. If the wall is STILL >93s on a clean re-run with no pruner interference, THAT is new information worth reporting. You were RIGHT to refuse to fix it agent-side; scripts/ + cron are observer-owned. Your other find — verify.sh:239 greps `MEAN FIDELITY` while fidelity.rs prints `MEAN VISUAL:`/`MEAN COVERAGE:`, so G1 reporting is blind though the floor still gates in Rust — is also mine and queued (could not patch it while verify.sh was mid-execution).%s\n" "$G$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\U0001F6D1 MEDIA BLOCKER — READ BEFORE THE NEXT VIDEO TICK (observer, tick 235; I checked the actual bytes)%s: MEDIA.md tick 1 decodes with %sopenh264, which is Constrained BASELINE ONLY%s — but BOTH committed video fixtures are %sH.264 HIGH profile (AVCProfileIndication=100)%s: engine/media/tests/data/bear-640x360-v-2frames_frag.mp4 (High, level 3.0) and blackwhite_yuv420p.mp4 (High, level 1.2). %sSo tick 1 will FAIL against its own fixture%s, and the failure will look like a wiring bug when it is an INPUT bug — expect to burn a tick or two deciding which. %sTHE FIX (cheap, everything needed is already on this box)%s: mint a Baseline fixture with the SYSTEM ffmpeg binary as a %sDEV TOOL%s — this does NOT violate no-ffmpeg, which forbids LINKING ffmpeg into the browser, not using it to author a test file: %sffmpeg -i engine/media/tests/data/bear-640x360-v-2frames_frag.mp4 -c:v libx264 -profile:v baseline -level 3.0 -movflags +frag_keyframe+empty_moov -an engine/media/tests/data/bear-baseline_frag.mp4%s (verify: the avcC profile byte must read 66, not 100). AV1 fixtures for the re_rav1d tick are ALSO already local and tiny: chromium/media/test/data/av1-I-frame-320x240 (4K), four-colors-av1.mp4 (4K), av1-film_grain.ivf (28K) — Chromium is BSD-3, so copy them in WITH provenance in a header comment. AUDIO: a real device EXISTS (HDA NVidia HDMI), so cpal is not blocked — but %sgate on decoded PCM SAMPLE CORRECTNESS, never on audible playback%s: a gate that needs a working sound card is a gate that false-REDs on a headless box.%s\n" "$R$B" "$O" "$R$B" "$O" "$R$B" "$O" "$R$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$C$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\U0001F501 PROCESS RULES (observer, tick 234 — from ENGINEERING.MD + the fidelity finding; full ledger: docs/ENGINEERING-SYNTHESIS.md). THESE BIND EVERY TICK: %s(1) THE CHECKLIST IS AN INPUT, FIDELITY IS THE GATE%s — Phase 0 exits on >=0.75 structural fidelity on >=95%% of Tranco top-1000 + >=0.70 per top-20 category, NOT on capability%%. Capability%% CANNOT see feature-present-but-site-broken. %s(2) RE-PROBE STALE UNKNOWNS BEFORE BUILDING THEM%s — WebAssembly, CJK line-breaking, media queries, hydration and the WHOLE OAuth redirect flow were all carried as unknown and ALL ALREADY WORKED. The checklist goes stale FROM OUR OWN LANDED TICKS. A cheap re-probe MUST precede any build tick aimed at an unknown. %s(3) EVERY GREEN MUST HAVE A DEMONSTRATED WAY TO GO RED%s — assert every scripted edit (cargo fmt reflows targets and silently voids replacements); no `if false` probes; a probe that cannot fail measured nothing. %s(4) PUBLISH, DO NOT REBUILD, THE ALREADY-WON%s — pure-Rust image decoders (image 0.25 + resvg, ZERO C image FFI => the libwebp CVSS-10 class is eliminated BY CONSTRUCTION today), swash shaping, occlusion-truthful hit-test, stable NodeIds, native tree-diff, memory-safe DOM/layout/paint. Do not spend ticks re-implementing these; the JS engine is the SOLE remaining memory-unsafe component. %s(5) NAMED LEVERS ONLY%s — never letter-code a set that collides with another decomposition (M-3 fidelity vs M3 symphonia cost a tick).%s\n" "$C$B" "$R$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$O"
printf "  %s⛔ PARKED (observer, tick 156): SKIP step-6 grid-template-areas — it burned 2h+ across session windows without landing (too big for one atomic tick; no taffy consumer = a subsystem, not a bounded fix). WIP is in git stash. Do NOT pick it; it needs a dedicated decomposition session. Pick the next BOUNDED lever instead (any of: overflow/position render steps, OR the pull-forward/T-tier levers below: U-3 SameSite, T0.4 CORS, T2 crypto.subtle/ReadableStream/:host, T4 forms POST/validation, T5 shell-persistence, T6.1 agent actuation — all ~1 bounded tick).%s\n" "$R$B" "$O"
printf "  %s🔀 DIVERSIFY (observer, tick 159): the RENDER sequence's REMAINING steps are SUBSYSTEM-SCOPE layout-math (grid[parked], z-index/sticky stacking, CSSOM .sheet) — TWO consecutive stalls (grid 2h, t159 86min WIP-discarded). ⚠ SUPERSEDED (observer t686): this tick-159 anti-CSS-layout steer is DEAD — the fidelity pivot proved GEOMETRY/PLACEMENT layout-math IS the binding Phase-0 constraint (placement 6.4%% corpus-wide) and it is now CO-#1 (rendering-gap block at the TOP). Layout is NO LONGER the tail to avoid; it is the MAIN LINE. Historical context only below: PICK FROM THE BOUNDED, HIGH-VALUE OTHER-TIER LEVERS (~20min each, daily-driver-critical, all UNBUILT): U-3 SameSite enforcement (storage.rs dead code); T0.4 CORS; T2 crypto.subtle+CSPRNG / ReadableStream+response.body(null today) / :host+::part selectors; T4 POST-navigation / multipart-FormData / constraint-validation; T5 shell bookmarks+settings+history persistence; T6.1 agent activate->Page::dispatch_click. Take a CSS-layout lever ONLY if it is a SINGLE bounded mechanism (<2 files, NO Taffy distribution/sizing/flex-algorithm math).%s\n" "$C$B" "$O"
# ── AUTO-PIVOT (observer, tick 193): systematized staleness detector replaces the one-off REFRESH note.
# It flags when recent ticks cluster in one engine subsystem with Phase-0 readiness flat, and prints the
# current biggest daily-driver holes (constellation --gaps) so the lever rotates to a NEW domain.
./scripts/lever-pivot.sh || true
printf "  html/dom (~93%%) is a done tail — a html/dom-flip tick does NOT advance the mandate. Correction: Taffy #204\n"
printf "  ('Support CSS Grid') SHIPPED; the intrinsic-sizing blocker is MANUK'S OWN leaf measure — fixable in a tick.\n"
printf "  %sRENDER+INTERACT SEQUENCE (build top-down; each bar = 'done for daily-driver'):%s\n" "$G$B" "$O"
printf "   %s1 Intrinsic sizing + wire calc()%s  bar: calc(100%%-250px) sidebar-split ~1px; border-box p-4 child=136px; css-sizing 12->35%%\n" "$G" "$O"
printf "   %s2 SPA link-intercept (a-click preventDefault cancels shell nav)%s  bar: React Link click => pushState, NO reload; push fires no popstate\n" "$G" "$O"
printf "   %s3 IntersectionObserver driven-on-scroll (verify E2E)%s  bar: headless scroll => 2nd screenful appends+fetches; multi-val rootMargin\n" "$G" "$O"
printf "   %s4 Block/inline edges (margin-collapse, %%-height, inline-space bug)%s  bar: 100vh hero exact; a<b>b</b> gains no space\n" "$G" "$O"
printf "   %s5 Flex common-case%s  bar: 3x flex-1 cards w/ long token don't overflow (~1px); justify-between edges exact; css-flexbox 6->25%%\n" "$G" "$O"
printf "   %s6 Grid common-case (WIRE grid-template-areas: no taffy consumer!)%s  bar: repeat(3,1fr) gap exact; areas holy-grail; css-grid 5->20%%\n" "$G" "$O"
printf "   %s7 Overflow scroll-container%s  bar: overflow-y:scroll reserves gutter; overflow:hidden = BFC contains floats\n" "$G" "$O"
printf "   %s8 Positioned + real z-index stacking + sticky in getBoundingClientRect%s  bar: z-50 modal over z-10 header; sticky rect==pinned top\n" "$G" "$O"
printf "   %s9 Runtime CSSOM .sheet bridge%s  bar: insertRule/adopted-sheets actually cascade (styled-components/Lit restyle)\n" "$G" "$O"
printf "  %sPARALLEL TRACK (layout-independent — pull forward on any crash / crash-gated tick):%s\n" "$C$B" "$O"
printf "   %sP-A Stability%s: catch_unwind at JS-native boundary + contain calc-size SIGSEGV (a crash = lose ALL tabs)\n" "$C" "$O"
printf "   %sP-B Agentic floor%s: occlusion-aware hit_test; enabled/stable Conditions; BiDi quiescence; WIRE script.evaluate (protocol.rs:481)\n" "$C" "$O"
printf "  %s⚡ PULL-FORWARD UNBLOCKS (S-sized, dependency-free, high-gating — take on any tick where a layout lever is blocked):%s\n" "$C$B" "$O"
printf "   %sU-1 fetch req body+headers%s: closure is Fn(&str,&str) (event_loop.rs:1760) — POST body + Authorization DROPPED; response.headers always null. Widen it. (silent-fail class)\n" "$C" "$O"
printf "   %sU-2 streaming download-to-disk%s: downloads buffer in RAM + inherit the 30s doc timeout (page/lib.rs:3363) — multi-GB HF weights OOM/timeout. Route attachments through fetch_streaming. (best ROI/tick)\n" "$C" "$O"
printf "   %sU-3 SameSite/prefix enforcement%s: storage.rs (the ONLY SameSite enforcement) is DEAD CODE, 0 callers — live path is a flat jar. Wire it + __Host-/__Secure- prefixes. (login correctness)\n" "$C" "$O"
printf "  %sTHEN media (BIND GStreamer, never write a codec; lead WebM/VP9/Opus):%s M0 video box+reflector -> M1 src= play ->\n" "$Y$B" "$O"
printf "   M2 MediaSource/SourceBuffer (honest 'buffered' TimeRanges) -> M3 hls.js/dash.js unmodified -> M4 ABR+YouTube(clear only; Widevine=gap).\n"
printf "   %s(media is v1-OPTIONAL for the 'document+download web' milestone — build only if YouTube-class watch is declared; M-track foundation is XL not L)%s\n" "$Y" "$O"
printf "  %sTHEN full-tier sequence (transport/JS-platform/shadow-DOM/forms/shell/agentic — lowest-numbered unmet; falsifiable bar, NOT WPT%%; full map: reference/cap-research/ROADMAP.md):%s\n" "$G$B" "$O"
printf "   %sT0 transport enforcement%s: T0.4 CORS (0 hits — cross-origin fetch must reject; preflight; credentials) [M];  T0.5 CSP (0 hits) [fold into security sweep]\n" "$G" "$O"
printf "   %sT1 render polish%s: object-fit/object-position + aspect-ratio [S]; unicode-range parse+gate [S-M]; @font-face descriptors + size-adjust [M]; text-metric CSS (letter/word-spacing,text-transform,word-break,overflow-wrap) [M-L]\n" "$G" "$O"
printf "   %sT2 JS platform%s: boot-global sweep (verify Proxy traps) [S]; crypto.subtle + CSPRNG off Math.random [M]; ReadableStream + response.body (null today) [M]; :host/::part selectors (0 hits — YouTube/Lit visual fix) [M]\n" "$G" "$O"
printf "   %sT2b shadow-DOM%s: custom-element lifecycle (disconnectedCallback/slotchange/HTMLSlotElement/real instanceof) [L, needs per-tag reflector prototypes]; shadowRoot .host/.mode/closed-null + event retargeting [M]\n" "$G" "$O"
printf "   %sT4 forms%s: POST navigation (refuse-LOUD never GET-downgrade; net already POSTs) [S-M]; multipart->nav + FormData file bodies (urlencodes files today=silent drop) [M]; constraint validation (checkValidity/:invalid hard-coded valid) [M]\n" "$G" "$O"
printf "   %sT5 shell persistence%s: persist bookmarks+settings+a (url,title,visit_count,last_visit) history table (all evaporate on quit) [S-M]; per-origin Preferences store [S]; download progress+persisted list [S-M]\n" "$G" "$O"
printf "   %sT6 agentic actuation%s: T6.1 route agent activate/click_at through Page::dispatch_click (fires NO DOM events today — div-onclick SPA buttons un-actionable; dispatch_click already works in GUI) [M, HIGHEST-LEVERAGE agentic]; typing fires input/keydown [M]; BiDi loopback+auth [S]\n" "$G" "$O"
printf "   %sT4.4 passwords (LAST big table-stakes)%s: save-prompt + fill-picker + keyring-unlock — crypto core DONE in store/lib.rs (> Chromium-Linux bar); the iceberg is UX not crypto [L]\n" "$G" "$O"
printf "  %sPOLISH (after table-stakes)%s: IndexedDB MVP [L-XL, keep ABSENT until done — half-built is worse]; dedicated Web Workers [L]; CSSOM .sheet cascade bridge (step 9) [M-L]; variable/graded fonts+RTL [M]; date/range/color widgets [M]; about: pages + settings UI [M]; profiles/incognito [M]; BiDi script.evaluate+keyboard [L].\n" "$Y" "$O"
printf "  %sSKIP v1 (write the deferral down)%s: HTTP/3/QUIC, zstd, coalescing, OCSP (dead), Privacy Sandbox (dead), Service Worker runtime (XL), WebGL, contenteditable/IME, in-engine PDF render (download != render), Widevine (permanent), address/CC autofill, OS process sandbox (explicit non-goal).\n" "$Y" "$O"
printf "  %s⚑ BOT-WALL (separate track, NOT engine work; user: OUT of scope)%s: API-first for Greenhouse/Lever (public no-auth JSON APIs); spoof a Chrome UA by default (get past UA sniffers only); real-Chrome/CDP fallback for IG/X/YouTube; accept the gate + Widevine gap. Do NOT fingerprint-match Manuk's own stack (perishable treadmill; internal-inconsistency = worse than 'unknown client').\n" "$R$B" "$O"
printf "  %s⚡ INNER-LOOP VELOCITY (agent behavior — fewer edit->compile cycles, no rigor drop):%s cargo CHECK before cargo TEST (compile-error turns skip the 350MB mozjs link); do NOT pre-run verify.sh as a green-check (tick.sh owns the single wall — pre-running pays TWO); iterate on the ONE target gate, full 65-gate wall only at tick.sh landing.\n" "$C$B" "$O"
printf "  %sTHEN%s a reasonable security sweep (T0.5 CSP, codec licensing, capability scoping, POST-never-downgraded-to-GET, BiDi loopback default, OS-sandbox-is-a-v1-non-goal).\n\n" "$Y$B" "$O"

awk -F'\t' -v B="$B" -v C="$C" -v G="$G" -v Y="$Y" -v O="$O" -v TGT="$TARGET" '
  NR>1 && $1!="TOTAL" && $1!="encoding" {
    p+=$2; t+=$3
    fail=$3-$2
    if (fail>0) { af[$1]=fail; ap[$1]=$4 }
  }
  END {
    pct = t>0 ? 100*p/t : 0
    need = TGT/100*t - p
    printf "%s══ PROGRESS TALLY ══%s\n", B, O
    printf "  reachable (excl encoding tail): %s%d / %d = %.1f%%%s\n", G, p, t, pct, O
    printf "  daily-driver MVP diagnostic:    %d%% reachable  →  %s%d subtests to go%s\n", TGT, Y, (need>0?need:0), O
    printf "\n%s══ LEVER BOARD — PHASE: pick CSS-LAYOUT / media rows first (★), regardless of flip-rate ══%s\n", B, O
    printf "  %-22s %8s %7s  %s\n", "area", "failing", "pass%", "class"
    # sort areas by failing desc (simple insertion into an index array)
    n=0; for (k in af) { key[n++]=k }
    for (i=0;i<n;i++) for (j=i+1;j<n;j++) if (af[key[j]]>af[key[i]]) { tmp=key[i]; key[i]=key[j]; key[j]=tmp }
    for (i=0;i<n;i++) {
      a=key[i]
      cls = (a ~ /flex|grid|sizing|align|overflow|position|display|contain|multicol|break|masking|transform|css-values|css-color|css-backgrounds|css-ui/) ? "★ CSS-LAYOUT — DAILY-DRIVER (build now)" \
          : (a ~ /media|video|audio/) ? "★ MEDIA — DAILY-DRIVER (build now)" \
          : (a ~ /^dom$|html\/dom|selectors|domparsing|cssom|css-fonts/) ? "html/dom (reasonably done — deprioritise)" : "mixed"
      col = (cls ~ /DAILY-DRIVER/) ? G : Y
      printf "  %s%-22s %8d %6.1f%%  %s%s\n", col, a, af[a], ap[a], cls, O
    }
  }' "$A"
printf "\n%s══ DAILY-DRIVER PRIORITY LEVERS — research-informed; weigh ALONGSIDE the raw board (undervalued by raw count) ══%s\n" "$B" "$O"
printf "  (full map + per-site deps + forecast method: %sdocs/wiki/lever-map.md%s)\n" "$C" "$O"
printf "  The board above ranks by WPT MASS and has a KNOWN BLIND SPOT: it hides cheap, boot-critical APIs whose\n"
printf "  absence BLANK-SCREENS whole SPAs. Weigh by daily-driver UNLOCK, not raw subtest count:\n"
printf "  %s⚡ BOOT-CRITICAL — do FIRST despite low WPT mass (cheap, high-gating):%s\n" "$G" "$O"
printf "     • IntersectionObserver/ResizeObserver  — x.com + Instagram feeds are DEAD without IO   (S, 402 WPT)\n"
printf "     • History / pushState                  — every SPA nav degrades to a full page reload  (S, ~1k WPT)\n"
printf "     • Proxy/Reflect + microtask/MessageChannel — Vue3 reactivity silently dead w/o Proxy    (S-M)\n"
printf "     • Fetch + ReadableStream body          — gates Next.js RSC navigation                  (M, ~19k WPT)\n"
printf "  %s⚡ STEP-FUNCTION — largest raw levers, fully daily-driver:%s\n" "$C" "$O"
printf "     • Flex/Grid intrinsic sizing (min/max-content; Taffy #204) — M-L, ~28k WPT, every site\n"
printf "     • Web fonts (@font-face / WOFF2)                           — M, 8.8k WPT, layout-metric fidelity\n"
printf "     • Shadow DOM + Custom Elements                             — L, 20k WPT, YouTube / web-components\n"
printf "  %sMSE/MEDIA is now a PHASE PRIORITY (not deferred)%s — bind GStreamer/FFmpeg, don't hand-write codecs.\n" "$G" "$O"
printf "  %sDEFER (only these)%s: compositor-threaded scrolling, CSS containment/content-visibility (low value, high cost).\n" "$Y" "$O"
printf "  %sWeight by MANUK'S OWN pass-rate (the TALLY above), never Chrome's%s: an area near 100%% HERE is a done tail,\n" "$Y" "$O"
printf "     but an area still far from 100%% here (e.g. dom) has real high-flip gaps — keep grinding those. The research's\n"
printf "     'giant is done' notes are CHROME's numbers; MANUK's measured failing subtests are ground truth and win.\n"
printf "  %sNEXT this phase%s: CSS flex/grid INTRINSIC SIZING (min/max-content, Taffy #204)  ->  more CSS layout  ->  MSE media pipeline.\n" "$G" "$O"
printf "  %sFORECAST before building%s: cluster the failing subtests by ERROR-SIGNATURE — the biggest same-signature\n" "$B" "$O"
printf "     cluster means one fix flips them all (how tick-113 landed +10,249). See docs/wiki/lever-map.md #forecast.\n"
printf "\n%sHOW TO USE (agent):%s Obey the PHASE MANDATE at the top — pick a CSS-LAYOUT (★) or MEDIA tick, NOT html/dom flip.\n" "$B" "$O"
printf "  Run \`manuk-wpt wpt css/css-flexbox --show-failures\` (or css-grid/css-sizing) for the failure histogram; the top\n"
printf "  mechanism there IS the tick. A layout fix that makes real pages render correctly beats a bigger html/dom +N.\n"
printf "  For media: there is little WPT to chase — build the MediaSource/SourceBuffer surface + a GStreamer/FFmpeg bind,\n"
printf "  and gate it with a falsifiable capability test (a sample stream buffers + plays), not a WPT count.\n"
