#!/usr/bin/env bash
# ── LEVER BOARD — the biggest-impact-first work list + progress tally. The observer owns this; the agent
# CONSULTS it to pick the next tick so it attacks the broadest-impact mechanism first, not a narrow win.
#
# Ranks reachable areas by FAILING subtests, split by FLIP-RATE class: HIGH-FLIP areas (DOM/CSSOM/API/
# selector/parsing surfaces) yield many green subtests per fix; LAYOUT areas (flex/grid/sizing/…) are a
# multi-assertion slog (one fix flips ~nothing) — big in raw count but low yield. Exhaust high-flip mass
# FIRST. The encoding tail is out of v1 scope (V1-SCOPE.md) and excluded from the reachable tally.
#   usage: scripts/lever-board.sh
set -uo pipefail
cd "$(dirname "$0")/.."
A=docs/loop/WPT-AREAS.tsv
B=$'\033[1m'; C=$'\033[36m'; G=$'\033[32m'; Y=$'\033[33m'; O=$'\033[0m'
TARGET=83   # daily-driver MVP DIAGNOSTIC: reachable (non-tail) pass-rate goal. Real bar = real-site drivability.

# ── WORKFLOW WARNING (observer, tick 134). This has HUNG the loop 3× and needed a manual kill each time:
R=$'\033[31m'
printf "%s⚠ NEVER poll with a pgrep-of-your-own-pattern wait loop%s — e.g. \`while pgrep -f \"cargo test X\"; do sleep; done\`\n" "$R$B" "$O"
printf "  or \`until ! pgrep -f \"scripts/tick.sh\"; do ...; done\`. The pattern string is in the WAIT LOOP'S OWN cmdline, so\n"
printf "  pgrep always matches itself, never returns empty, and the loop spins FOREVER even after the real job finished.\n"
printf "  Instead: run cargo/tick.sh/tests in the FOREGROUND and let them block. If the harness backgrounds a long command,\n"
printf "  wait on its OUTPUT-FILE CONTENT (e.g. \`grep -q 'VERIFY:' out\`), never on pgrep of a string your wait command contains.\n\n"

# ── PHASE MANDATE (observer, tick 138+) — DAILY-DRIVER CAPABILITY via a FIXED SEQUENCE. ENFORCED. Full roadmap +
# good-enough bars + agentic fallbacks: docs/wiki/lever-map.md. Agent picks the LOWEST-NUMBERED unmet target.
printf "%s🎯 PHASE MANDATE — pick the LOWEST-NUMBERED unmet target below. Falsifiable bar, NOT WPT%%.%s\n" "$R$B" "$O"
printf "  %s\U0001F3AF PHASE 0 = THE FULL DAILY-DRIVER CHECKLIST, not the 5 finish-line levers (CORRECTED, tick 222). Those 5 (streaming/a11y-states/WebSocket/scroll-anchor/forced-reflow) were a MILESTONE. Phase 0 is COMPLETE ONLY WHEN THE BROWSER WORKS ON ~ALMOST EVERY WEBSITE across ALL classes (doc/app+hydration/social-feeds/platform-realtime/MEDIA) — tracked by scripts/phase0-progress.sh (now ~44%%: doc 44 / app 64 / platform 30 / MEDIA 5 / cross 48) — until every CRITICAL/reachable edge is works|gated and only the honest OUT-OF-REACH set (canvas office-suites, heavy-WebGL, DRM) is unmet. GRIND THE FULL CHECKLIST (constellation --gaps + DAILY-DRIVER-EDGES.md). TOP REMAINING, BORROW where possible: (1) MEDIA/YouTube [5%% — biggest gap; MSE -> symphonia(demux+AAC)+cpal(audio)+libvpx/rav1d(VP9/AV1) -> <video> playback+sync -> controls; VP9+AAC via isTypeSupported; no ffmpeg; DRM out]. (2) PROBE the 35 UNKNOWNS [cheap, many already work — ? outranks X]. (3) IndexedDB [borrow redb/heed — unblocks AWS/GCP]. (4) completeness identity [software-WebGL+honest-strings, visibilityState, permissions.query, userAgentData]. (5) canvas fillText raster. (6) clipboard.read/file-input/actuation-completers. (7) [PRUNED tick 234 — BELOW THE ROI LINE per ENGINEERING.MD Domain D: do NOT spend ticks on DEEP MathML, EXOTIC bidi edge cases, or ancient DOM quirks (document.all beyond truthiness, event.srcElement chains). Basic bidi + CJK line-breaking already measured WORKING. Excluded WITH EVIDENCE, not neglected.] (8) platform holes (Service Worker, WebGL). DO NOT declare Phase 0 done or trigger Phase 1 until the checklist is substantially met.%s\n" "$C$B" "$O"
printf "  %s▶ CO-#1 PRIORITIES (user directive, tick 223) — work these toward the 'IT DOES ALMOST EVERYTHING' full-checklist Phase-0 bar. They are CO-EQUAL; pick any; RE-READ THIS BOARD EACH TICK (priorities update mid-run). BORROW where possible, GATE each with a falsifiable check, land via tick.sh: %s(A) MEDIA/YouTube%s — M1 MSE skeleton -> M2 arraybuffer/Range -> M3 symphonia demux(fMP4/webm) -> M4 AAC+cpal audio -> M5 decode -> M6 <video> playback+A/V-sync -> M7 controls+WebVTT; DRM out. %s[CORRECTED tick 235 — the board was STALE and docs/loop/MEDIA.md is RIGHT: follow MEDIA.md, not this line. VP9 is LEFT ON THE FLOOR (no usable Rust decoder, stale C bindings, maintenance mode) so do NOT wire libvpx and do NOT steer isTypeSupported to VP9. `rav1d` upstream has NO Rust API (C-ABI drop-in for libdav1d) — use the `re_rav1d` fork (BSD-2, pure Rust). Ladder is openh264(Baseline) -> ... -> re_rav1d(AV1).]%s %s(B) OAUTH LOGIN%s — O1 redirect flow e2e -> O2 interactive iframe RE-RENDER(row 50; also fixes 3DS) -> O3 popup+postMessage -> O4 3rd-party/cross-site cookies -> O5 FedCM navigator.credentials; ASSURE via a REAL-PROVIDER MATRIX gate (Google GIS/GitHub/MS/Apple/Auth0/Okta round-trips). %s(C) canvas fillText%s — HIGH-LEVERAGE: wire the EXISTING engine/text swash glyph-raster to the 2D ctx; unlocks Google Docs/Sheets VIEWING + chart labels + xterm terminals in ONE fix. %s(D) FID-SWEEP [PROMOTED TO CO-#1, tick 235]%s — the broad 281-site category-stratified fidelity sweep is NOT an "interleave when blocked" item: it is THE EXIT GATE for the phase we are in, so it ranks WITH media/OAuth, not below them. Details in the CO-#2 block below (separate script, OFF the per-tick path, banks to RATCHET.tsv). MEASURED BIAS this corrects: of the last 40 landed ticks, 6 were measurement and ZERO were seams — ~85%% went to visible capability, because "media M3 works" is a satisfying tick line and "a trait boundary that changes no behavior" is not. Yet the measurement ticks were the HIGHEST-YIELD ones we ran (t225/t226 found WebAssembly, CJK, media queries, hydration and the whole OAuth redirect flow ALREADY WORKING). %s(E) PROBE the remaining UNKNOWNS%s — cheap constellation '?' probes (measure-and-pin like hydration); each flips a cell + validates the checklist. THEN the rest of constellation --gaps + DAILY-DRIVER-EDGES.md. Phase 0 = the FULL checklist met (almost every website), never a subset.%s\n" "$G$B" "$R$B" "$O" "$R$B" "$O" "$C$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$O"
printf "  %s🔬 TAKE FID-SWEEP FIRST (observer, tick 233) — THE BIGGEST UNKNOWN IN THE PROJECT, and it is CHEAP because the pieces already exist. TODAY the G1 fidelity gate runs TWO static doc pages (news.ycombinator.com + a Wikipedia article) and scores 75.8%% visual / 100%% coverage. But docs/bench/oracle-corpus.txt holds 281 CATEGORY-STRATIFIED sites and its own header warns that a tiny corpus is an ANECDOTE: 'the bugs we had NOT found were exactly the ones no corpus site happened to use'. So 75.8%% on our EASIEST class tells us nothing about app/social/platform sites — and capability%% CANNOT see feature-present-but-site-broken. Grinding media to 100%% while blind to app-class fidelity is optimizing the metric we can see. %s⚠ CRITICAL DESIGN CONSTRAINT: do NOT wire 281 sites into verify.sh%s — each site is a render + Chrome compare; that would blow the WALL ratchet and brick every tick. Build a SEPARATE sweep (e.g. scripts/fidelity-sweep.sh) that runs the broad corpus OFF the per-tick path, writes a per-CATEGORY score table, and BANKS a headline number into RATCHET.tsv (there is currently NO fidelity mark there). Keep the per-tick G1 gate small and fast (2-5 sites) exactly as it is. DELIVERABLE: a category-stratified fidelity table (doc/app/social/platform/media) so we learn whether app-class sites actually WORK. That number redirects everything downstream and may show we are closer OR much further than 52%% capability suggests.%s\n" "$Y$B" "$R$B" "$O" "$O"
printf "  %s▶ CO-#2 SEAMS + MEASUREMENT [named, NOT letter-coded: M1-M7 below are MEDIA steps and must never be confused with these] (observer, tick 232 — from ENGINEERING.MD; full synthesis: docs/ENGINEERING-SYNTHESIS.md). Track C (CO-#1 above) stays the MAIN LINE and is unchanged. These INTERLEAVE: take ONE when a CO-#1 lever is blocked, stalled, or crash-gated. RATIONALE: these are SEAMS that are cheap NOW and cost MULTIPLES to retrofit, plus MEASUREMENT that redirects everything else. %sSEAM-JSENGINE%s — extract a trait boundary around mozjs (realms, GC handles, host hooks, module loading, microtask queue); ONE impl (mozjs); do NOT write a second engine. Gate: every JS call site routes through the trait, all JS gates still pass. HIGHEST-REGRET DEFERRAL IN THE REPORT. %sSEAM-TAINT%s — mark content-originated DOM strings TAINTED; add a task-scoped capability-token type. INERT at first: the BOUNDARY is the deliverable, enforcement is Phase 2. Prompt injection is unsolvable at the model layer, so it must be structural. %sSEAM-NOPIXELS%s — a flag in the paint path: layout + a11y tree, paint ELIDED. Gate: an agent tab yields a correct a11y tree with ZERO display items. Saves the whole raster+GPU+composite budget per background tab. %sSEAM-NODEID%s — GATE that node identity survives re-render/hydration; publish the contract (kills the #1 source of agent flakiness). %sMEM-HARNESS%s — RSS+PSS via /proc/PID/smaps_rollup, Tranco top-100 category-stratified, hold at 10/50/100 tabs, report median+p90 per-tab RSS. THIS CAN FALSIFY OUR OWN POSITIONING (within 20%% of Chrome = drop the memory claim) — that is the point; measure before marketing. %sTRI-ORACLE%s — add Firefox as a 2nd reference; flag ONLY diffs where Manuk disagrees with BOTH (Chromium-only diffing overfits to Chromium bugs). %sFID-SWEEP%s — wire structural fidelity to the REAL Phase-0 exit rule: >=0.75 on >=95%% of top-1000 + >=0.70 per top-20 category. The 128-cap checklist is the INPUT; this is the GATE.%s\n" "$Y$B" "$R$B" "$O" "$R$B" "$O" "$C$B" "$O" "$C$B" "$O" "$G$B" "$O" "$G$B" "$O" "$G$B" "$O" "$O"
printf "  %s\U0001FA7A RUN scripts/agent-doctor.sh IF ANYTHING FEELS STUCK (observer, tick 235)%s — it answers the one question liveness checks miss: %sis work LANDING?%s It probes tick-cadence stall, GATE ARITHMETIC (whether the ratchet mark makes landing mathematically impossible — the exact thing that silently ate tick 235 for 3h while every health signal read green), command-repetition loop signatures, verify-retry loops, staged-work stagnation, parked wip/ branches, and observer contention. %sTWO THINGS WAITING FOR YOU RIGHT NOW%s: (1) the pruner/wall race is FIXED for real this time — the stem prune is no longer skipped, it is now restricted to duplicates OLDER THAN THE RUNNING BUILD's start time, so it keeps reclaiming (31G in one live pass) while never touching your working set. Re-run the wall; it should come in warm. (2) %sYour tick-235 work is parked on branch wip/tick235-media-m4%s — you saved it correctly rather than lose it, and you were right to use --no-verify there to avoid committing my in-flight scripts/ edits. Once ONE verify lands under the 93s ceiling and status-update.sh banks it, cherry-pick that branch and land it. Do not redo the work.%s\n" "$C$B" "$O" "$Y$B" "$O" "$G$B" "$O" "$G$B" "$O" "$O"
printf "  %s\u26A1 WALL 911s IS MINE AND SELF-CLEARING — DO NOT DEBUG IT (observer, tick 265)%s. I set `debug = 1` in the root Cargo.toml profile to stop /home hitting ENOSPC (93%% full; 78G of test binaries, 175MB of DWARF each). That invalidated every fingerprint, so ONE full rebuild ran and its 911s got banked as a green receipt — which is why the ratchet refuses right now. %sThe cache is already warm again (workspace build 0.44s, gate bin 0.36s, verified twice)%s, so your NEXT verify comes in near 64s, status-update banks it, and the block lifts by itself. Binaries went 552MB -> 350MB and disk 93%% -> 81%%. %sSo: just run your tick normally. Do NOT hunt the wall, do NOT touch Cargo.toml, do NOT re-derive this.%s If a verify comes back >200s on a WARM tree, THAT is new and worth reporting (use the twice-test: run the same cargo command twice — if the 2nd is not instant, something is deleting the working set). %sAlso: I am running FID-SWEEP myself right now%s (60 stratified sites, --jobs 1, off the tick path) so you do NOT need to — it is the Phase-0 exit gate and it had never been run. I will bank the headline. Take the NEXT item on the pivot list instead: %sIndexedDB (borrow redb/heed), then Service Worker + Cache API, container queries, AVIF%s.%s\n" "$Y$B" "$O" "$G$B" "$O" "$R$B" "$O" "$C$B" "$O" "$G$B" "$O" "$O"
printf "  %s\U0001F500 PIVOT — MEDIA IS DONE, MOVE OFF IT (observer, tick 264)%s. Media went %s5%% -> 45%%%s across ticks 240-264 and the class is now essentially complete: video_decode, G_MEDIA_AAC, playback_clock, av_sync, G_VIDEO_FRAME, vtt_captions/G_TEXT_TRACKS/G_CUE_CHANGE, G_MSE, G_MEDIA_SEGMENT_FETCH all gated, and tick 263 put moving pictures on a real page. The ONLY media rows left are %saudio output device%s (one bounded tick — and GATE ON DECODED PCM, never audible playback: a gate needing a sound card false-REDs) and media pseudo-classes; %sEME/Widevine is deliberately OUT OF SCOPE — do not touch it%s. OAuth (O1-O5 + FedCM) and canvas fillText have ALSO landed. Readiness overall 52%% -> 62%%. %s▶ NEW CO-#1, in this order:%s %s(1) RUN FID-SWEEP FOR REAL%s — scripts/fidelity-sweep.sh exists and has NEVER been run broadly (results.tsv holds only a 16-row pilot). It is the PHASE-0 EXIT GATE (>=0.75 placement fidelity on >=95%% of the corpus + >=0.70 per category) and we still cannot say whether app/social/platform sites actually WORK. Run it OFF the tick path (--jobs 1 while the agent builds), bank the headline into RATCHET.tsv. Gate on PLACEMENT, not COVERAGE — coverage saturates at 100%% on visibly broken pages. %s(2) IndexedDB%s (borrow redb/heed — AWS/GCP consoles hard-fail without it). %s(3) Service Worker + Cache API%s (offline/PWA/instant repeat visits). %s(4) container queries%s (the biggest CSS shift in a decade; component-responsive layout). %s(5) AVIF%s (modern sites serve it FIRST — a missing decoder is a blank hero image). %s(6) Web Workers, scroll snap, CSP enforcement%s. %s(7) the 37 remaining UNKNOWNS%s — still the cheapest yield we have; t225/t226 found five capabilities already working. WebGL stays honestly out-of-reach for now.%s\n" "$G$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$R$B" "$O" "$R$B" "$O" "$R$B" "$O" "$C$B" "$O" "$C$B" "$O" "$C$B" "$O" "$C$B" "$O" "$Y$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\U0001F680 THE WALL IS FIXED — LAND YOUR FOUR PARKED TICKS NOW (observer, tick 235)%s. Root cause found and closed: %sverify.sh builds manuk-page under TWO feature sets (spidermonkey / stylo,spidermonkey), cargo emits BOTH under the SAME name-stem with different hashes, and my disk-hygiene stem prune (\"keep newest per stem\") deleted the second variant every 3 minutes%s — so every wall relinked ~23 mozjs test binaries. MEASURED: with both variants present cargo reports 380 units Fresh in 0.26s; after a prune the same build cost 11-23s. That gap x23 gates IS the 363 unaccounted seconds and the 5x regression (48-80s at ticks 117-128 -> 426s). Fixed with a 12h age floor on the stem prune. %sVERIFIED NOW: g_globals 0.47s, g_lifecycle 0.45s, g_selector 0.40s%s (was 11-23s each). Also fixed: the ratchet no longer deadlocks on an UNTRUSTED wall (it blocks only on a GREEN receipt, else advisory), the parity gate no longer false-REDs when the oracle drops pages (65/65 across 27 pages is a 100%% pass rate, not a failure — it retries once), status-update now runs BEFORE the ratchet judges, and it only banks a wall from a GREEN run. %sSO: run ONE verify. It should come in near the historical 48-80s. Then land all four in order: wip/tick235-media-m4, wip/tick236-media-m5, wip/tick237-canvas-drawimage, wip/tick238-probe-stale-rows.%s They are complete and green — cherry-pick, do NOT redo. If the wall is STILL slow after this, that is genuinely new information: capture prewarm_launch_seconds + unattributed_seconds from the receipt (both now recorded) and report them rather than re-deriving.%s\n" "$G$B" "$O" "$R$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\u2705 WALL-vs-HYGIENE RACE — FIXED, STOP RE-DIAGNOSING IT (observer, tick 235)%s: your memory `wall-vs-hygiene-cron-race` was CORRECT and the bug was MINE. I tightened the disk-hygiene cron to */3 while a verify wall runs 8-13min, so it pruned 3-4x MID-WALL and deleted the test binaries + release manuk-wpt that verify was about to run — hence sub-second cargo commands but a 480-800s aggregate against a 93s ceiling. %sFIXED in scripts/disk-hygiene.sh: the deps prunes are SKIPPED whenever rustc/cargo is live%s (safety valve: they still run if free disk <=25G, since ENOSPC beats a slow wall). Verified live — with 8 rustc running it prints \"deps prune SKIPPED\". ACTIVE ALREADY; cron execs from disk, no commit needed. %sSo just RE-RUN THE WALL.%s It should fall back toward the warm 50-70s range. Do NOT spend more ticks on cargo timing measurements, headless-gate feature thrash, or re-deriving the cause — that ground is covered. If the wall is STILL >93s on a clean re-run with no pruner interference, THAT is new information worth reporting. You were RIGHT to refuse to fix it agent-side; scripts/ + cron are observer-owned. Your other find — verify.sh:239 greps `MEAN FIDELITY` while fidelity.rs prints `MEAN VISUAL:`/`MEAN COVERAGE:`, so G1 reporting is blind though the floor still gates in Rust — is also mine and queued (could not patch it while verify.sh was mid-execution).%s\n" "$G$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\U0001F6D1 MEDIA BLOCKER — READ BEFORE THE NEXT VIDEO TICK (observer, tick 235; I checked the actual bytes)%s: MEDIA.md tick 1 decodes with %sopenh264, which is Constrained BASELINE ONLY%s — but BOTH committed video fixtures are %sH.264 HIGH profile (AVCProfileIndication=100)%s: engine/media/tests/data/bear-640x360-v-2frames_frag.mp4 (High, level 3.0) and blackwhite_yuv420p.mp4 (High, level 1.2). %sSo tick 1 will FAIL against its own fixture%s, and the failure will look like a wiring bug when it is an INPUT bug — expect to burn a tick or two deciding which. %sTHE FIX (cheap, everything needed is already on this box)%s: mint a Baseline fixture with the SYSTEM ffmpeg binary as a %sDEV TOOL%s — this does NOT violate no-ffmpeg, which forbids LINKING ffmpeg into the browser, not using it to author a test file: %sffmpeg -i engine/media/tests/data/bear-640x360-v-2frames_frag.mp4 -c:v libx264 -profile:v baseline -level 3.0 -movflags +frag_keyframe+empty_moov -an engine/media/tests/data/bear-baseline_frag.mp4%s (verify: the avcC profile byte must read 66, not 100). AV1 fixtures for the re_rav1d tick are ALSO already local and tiny: chromium/media/test/data/av1-I-frame-320x240 (4K), four-colors-av1.mp4 (4K), av1-film_grain.ivf (28K) — Chromium is BSD-3, so copy them in WITH provenance in a header comment. AUDIO: a real device EXISTS (HDA NVidia HDMI), so cpal is not blocked — but %sgate on decoded PCM SAMPLE CORRECTNESS, never on audible playback%s: a gate that needs a working sound card is a gate that false-REDs on a headless box.%s\n" "$R$B" "$O" "$R$B" "$O" "$R$B" "$O" "$R$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$C$B" "$O" "$Y$B" "$O" "$O"
printf "  %s\U0001F501 PROCESS RULES (observer, tick 234 — from ENGINEERING.MD + the fidelity finding; full ledger: docs/ENGINEERING-SYNTHESIS.md). THESE BIND EVERY TICK: %s(1) THE CHECKLIST IS AN INPUT, FIDELITY IS THE GATE%s — Phase 0 exits on >=0.75 structural fidelity on >=95%% of Tranco top-1000 + >=0.70 per top-20 category, NOT on capability%%. Capability%% CANNOT see feature-present-but-site-broken. %s(2) RE-PROBE STALE UNKNOWNS BEFORE BUILDING THEM%s — WebAssembly, CJK line-breaking, media queries, hydration and the WHOLE OAuth redirect flow were all carried as unknown and ALL ALREADY WORKED. The checklist goes stale FROM OUR OWN LANDED TICKS. A cheap re-probe MUST precede any build tick aimed at an unknown. %s(3) EVERY GREEN MUST HAVE A DEMONSTRATED WAY TO GO RED%s — assert every scripted edit (cargo fmt reflows targets and silently voids replacements); no `if false` probes; a probe that cannot fail measured nothing. %s(4) PUBLISH, DO NOT REBUILD, THE ALREADY-WON%s — pure-Rust image decoders (image 0.25 + resvg, ZERO C image FFI => the libwebp CVSS-10 class is eliminated BY CONSTRUCTION today), swash shaping, occlusion-truthful hit-test, stable NodeIds, native tree-diff, memory-safe DOM/layout/paint. Do not spend ticks re-implementing these; the JS engine is the SOLE remaining memory-unsafe component. %s(5) NAMED LEVERS ONLY%s — never letter-code a set that collides with another decomposition (M-3 fidelity vs M3 symphonia cost a tick).%s\n" "$C$B" "$R$B" "$O" "$R$B" "$O" "$Y$B" "$O" "$G$B" "$O" "$Y$B" "$O" "$O"
printf "  %s⛔ PARKED (observer, tick 156): SKIP step-6 grid-template-areas — it burned 2h+ across session windows without landing (too big for one atomic tick; no taffy consumer = a subsystem, not a bounded fix). WIP is in git stash. Do NOT pick it; it needs a dedicated decomposition session. Pick the next BOUNDED lever instead (any of: overflow/position render steps, OR the pull-forward/T-tier levers below: U-3 SameSite, T0.4 CORS, T2 crypto.subtle/ReadableStream/:host, T4 forms POST/validation, T5 shell-persistence, T6.1 agent actuation — all ~1 bounded tick).%s\n" "$R$B" "$O"
printf "  %s🔀 DIVERSIFY (observer, tick 159): the RENDER sequence's REMAINING steps are SUBSYSTEM-SCOPE layout-math (grid[parked], z-index/sticky stacking, CSSOM .sheet) — TWO consecutive stalls (grid 2h, t159 86min WIP-discarded). STOP mining the CSS-layout tail; the easy render levers are DONE (t150-158). PICK FROM THE BOUNDED, HIGH-VALUE OTHER-TIER LEVERS NOW (~20min each, daily-driver-critical, all UNBUILT): U-3 SameSite enforcement (storage.rs dead code); T0.4 CORS; T2 crypto.subtle+CSPRNG / ReadableStream+response.body(null today) / :host+::part selectors; T4 POST-navigation / multipart-FormData / constraint-validation; T5 shell bookmarks+settings+history persistence; T6.1 agent activate->Page::dispatch_click. Take a CSS-layout lever ONLY if it is a SINGLE bounded mechanism (<2 files, NO Taffy distribution/sizing/flex-algorithm math).%s\n" "$C$B" "$O"
# ── AUTO-PIVOT (observer, tick 193): systematized staleness detector replaces the one-off REFRESH note.
# It flags when recent ticks cluster in one engine subsystem with Phase-0 readiness flat, and prints the
# current biggest daily-driver holes (constellation --gaps) so the lever rotates to a NEW domain.
./scripts/lever-pivot.sh || true
printf "  html/dom (~93%%) is a done tail — a html/dom-flip tick does NOT advance the mandate. Correction: Taffy #204\n"
printf "  ('Support CSS Grid') SHIPPED; the intrinsic-sizing blocker is MANUK'S OWN leaf measure — fixable in a tick.\n"
printf "  %sRENDER+INTERACT SEQUENCE (build top-down; each bar = 'done for daily-driver'):%s\n" "$G$B" "$O"
printf "   %s1 Intrinsic sizing + wire calc()%s  bar: calc(100%%-250px) sidebar-split ~1px; border-box p-4 child=136px; css-sizing 12->35%%\n" "$G" "$O"
printf "   %s2 SPA link-intercept (a-click preventDefault cancels shell nav)%s  bar: React Link click => pushState, NO reload; push fires no popstate\n" "$G" "$O"
printf "   %s3 IntersectionObserver driven-on-scroll (verify E2E)%s  bar: headless scroll => 2nd screenful appends+fetches; multi-val rootMargin\n" "$G" "$O"
printf "   %s4 Block/inline edges (margin-collapse, %%-height, inline-space bug)%s  bar: 100vh hero exact; a<b>b</b> gains no space\n" "$G" "$O"
printf "   %s5 Flex common-case%s  bar: 3x flex-1 cards w/ long token don't overflow (~1px); justify-between edges exact; css-flexbox 6->25%%\n" "$G" "$O"
printf "   %s6 Grid common-case (WIRE grid-template-areas: no taffy consumer!)%s  bar: repeat(3,1fr) gap exact; areas holy-grail; css-grid 5->20%%\n" "$G" "$O"
printf "   %s7 Overflow scroll-container%s  bar: overflow-y:scroll reserves gutter; overflow:hidden = BFC contains floats\n" "$G" "$O"
printf "   %s8 Positioned + real z-index stacking + sticky in getBoundingClientRect%s  bar: z-50 modal over z-10 header; sticky rect==pinned top\n" "$G" "$O"
printf "   %s9 Runtime CSSOM .sheet bridge%s  bar: insertRule/adopted-sheets actually cascade (styled-components/Lit restyle)\n" "$G" "$O"
printf "  %sPARALLEL TRACK (layout-independent — pull forward on any crash / crash-gated tick):%s\n" "$C$B" "$O"
printf "   %sP-A Stability%s: catch_unwind at JS-native boundary + contain calc-size SIGSEGV (a crash = lose ALL tabs)\n" "$C" "$O"
printf "   %sP-B Agentic floor%s: occlusion-aware hit_test; enabled/stable Conditions; BiDi quiescence; WIRE script.evaluate (protocol.rs:481)\n" "$C" "$O"
printf "  %s⚡ PULL-FORWARD UNBLOCKS (S-sized, dependency-free, high-gating — take on any tick where a layout lever is blocked):%s\n" "$C$B" "$O"
printf "   %sU-1 fetch req body+headers%s: closure is Fn(&str,&str) (event_loop.rs:1760) — POST body + Authorization DROPPED; response.headers always null. Widen it. (silent-fail class)\n" "$C" "$O"
printf "   %sU-2 streaming download-to-disk%s: downloads buffer in RAM + inherit the 30s doc timeout (page/lib.rs:3363) — multi-GB HF weights OOM/timeout. Route attachments through fetch_streaming. (best ROI/tick)\n" "$C" "$O"
printf "   %sU-3 SameSite/prefix enforcement%s: storage.rs (the ONLY SameSite enforcement) is DEAD CODE, 0 callers — live path is a flat jar. Wire it + __Host-/__Secure- prefixes. (login correctness)\n" "$C" "$O"
printf "  %sTHEN media (BIND GStreamer, never write a codec; lead WebM/VP9/Opus):%s M0 video box+reflector -> M1 src= play ->\n" "$Y$B" "$O"
printf "   M2 MediaSource/SourceBuffer (honest 'buffered' TimeRanges) -> M3 hls.js/dash.js unmodified -> M4 ABR+YouTube(clear only; Widevine=gap).\n"
printf "   %s(media is v1-OPTIONAL for the 'document+download web' milestone — build only if YouTube-class watch is declared; M-track foundation is XL not L)%s\n" "$Y" "$O"
printf "  %sTHEN full-tier sequence (transport/JS-platform/shadow-DOM/forms/shell/agentic — lowest-numbered unmet; falsifiable bar, NOT WPT%%; full map: reference/cap-research/ROADMAP.md):%s\n" "$G$B" "$O"
printf "   %sT0 transport enforcement%s: T0.4 CORS (0 hits — cross-origin fetch must reject; preflight; credentials) [M];  T0.5 CSP (0 hits) [fold into security sweep]\n" "$G" "$O"
printf "   %sT1 render polish%s: object-fit/object-position + aspect-ratio [S]; unicode-range parse+gate [S-M]; @font-face descriptors + size-adjust [M]; text-metric CSS (letter/word-spacing,text-transform,word-break,overflow-wrap) [M-L]\n" "$G" "$O"
printf "   %sT2 JS platform%s: boot-global sweep (verify Proxy traps) [S]; crypto.subtle + CSPRNG off Math.random [M]; ReadableStream + response.body (null today) [M]; :host/::part selectors (0 hits — YouTube/Lit visual fix) [M]\n" "$G" "$O"
printf "   %sT2b shadow-DOM%s: custom-element lifecycle (disconnectedCallback/slotchange/HTMLSlotElement/real instanceof) [L, needs per-tag reflector prototypes]; shadowRoot .host/.mode/closed-null + event retargeting [M]\n" "$G" "$O"
printf "   %sT4 forms%s: POST navigation (refuse-LOUD never GET-downgrade; net already POSTs) [S-M]; multipart->nav + FormData file bodies (urlencodes files today=silent drop) [M]; constraint validation (checkValidity/:invalid hard-coded valid) [M]\n" "$G" "$O"
printf "   %sT5 shell persistence%s: persist bookmarks+settings+a (url,title,visit_count,last_visit) history table (all evaporate on quit) [S-M]; per-origin Preferences store [S]; download progress+persisted list [S-M]\n" "$G" "$O"
printf "   %sT6 agentic actuation%s: T6.1 route agent activate/click_at through Page::dispatch_click (fires NO DOM events today — div-onclick SPA buttons un-actionable; dispatch_click already works in GUI) [M, HIGHEST-LEVERAGE agentic]; typing fires input/keydown [M]; BiDi loopback+auth [S]\n" "$G" "$O"
printf "   %sT4.4 passwords (LAST big table-stakes)%s: save-prompt + fill-picker + keyring-unlock — crypto core DONE in store/lib.rs (> Chromium-Linux bar); the iceberg is UX not crypto [L]\n" "$G" "$O"
printf "  %sPOLISH (after table-stakes)%s: IndexedDB MVP [L-XL, keep ABSENT until done — half-built is worse]; dedicated Web Workers [L]; CSSOM .sheet cascade bridge (step 9) [M-L]; variable/graded fonts+RTL [M]; date/range/color widgets [M]; about: pages + settings UI [M]; profiles/incognito [M]; BiDi script.evaluate+keyboard [L].\n" "$Y" "$O"
printf "  %sSKIP v1 (write the deferral down)%s: HTTP/3/QUIC, zstd, coalescing, OCSP (dead), Privacy Sandbox (dead), Service Worker runtime (XL), WebGL, contenteditable/IME, in-engine PDF render (download != render), Widevine (permanent), address/CC autofill, OS process sandbox (explicit non-goal).\n" "$Y" "$O"
printf "  %s⚑ BOT-WALL (separate track, NOT engine work; user: OUT of scope)%s: API-first for Greenhouse/Lever (public no-auth JSON APIs); spoof a Chrome UA by default (get past UA sniffers only); real-Chrome/CDP fallback for IG/X/YouTube; accept the gate + Widevine gap. Do NOT fingerprint-match Manuk's own stack (perishable treadmill; internal-inconsistency = worse than 'unknown client').\n" "$R$B" "$O"
printf "  %s⚡ INNER-LOOP VELOCITY (agent behavior — fewer edit->compile cycles, no rigor drop):%s cargo CHECK before cargo TEST (compile-error turns skip the 350MB mozjs link); do NOT pre-run verify.sh as a green-check (tick.sh owns the single wall — pre-running pays TWO); iterate on the ONE target gate, full 65-gate wall only at tick.sh landing.\n" "$C$B" "$O"
printf "  %sTHEN%s a reasonable security sweep (T0.5 CSP, codec licensing, capability scoping, POST-never-downgraded-to-GET, BiDi loopback default, OS-sandbox-is-a-v1-non-goal).\n\n" "$Y$B" "$O"

awk -F'\t' -v B="$B" -v C="$C" -v G="$G" -v Y="$Y" -v O="$O" -v TGT="$TARGET" '
  NR>1 && $1!="TOTAL" && $1!="encoding" {
    p+=$2; t+=$3
    fail=$3-$2
    if (fail>0) { af[$1]=fail; ap[$1]=$4 }
  }
  END {
    pct = t>0 ? 100*p/t : 0
    need = TGT/100*t - p
    printf "%s══ PROGRESS TALLY ══%s\n", B, O
    printf "  reachable (excl encoding tail): %s%d / %d = %.1f%%%s\n", G, p, t, pct, O
    printf "  daily-driver MVP diagnostic:    %d%% reachable  →  %s%d subtests to go%s\n", TGT, Y, (need>0?need:0), O
    printf "\n%s══ LEVER BOARD — PHASE: pick CSS-LAYOUT / media rows first (★), regardless of flip-rate ══%s\n", B, O
    printf "  %-22s %8s %7s  %s\n", "area", "failing", "pass%", "class"
    # sort areas by failing desc (simple insertion into an index array)
    n=0; for (k in af) { key[n++]=k }
    for (i=0;i<n;i++) for (j=i+1;j<n;j++) if (af[key[j]]>af[key[i]]) { tmp=key[i]; key[i]=key[j]; key[j]=tmp }
    for (i=0;i<n;i++) {
      a=key[i]
      cls = (a ~ /flex|grid|sizing|align|overflow|position|display|contain|multicol|break|masking|transform|css-values|css-color|css-backgrounds|css-ui/) ? "★ CSS-LAYOUT — DAILY-DRIVER (build now)" \
          : (a ~ /media|video|audio/) ? "★ MEDIA — DAILY-DRIVER (build now)" \
          : (a ~ /^dom$|html\/dom|selectors|domparsing|cssom|css-fonts/) ? "html/dom (reasonably done — deprioritise)" : "mixed"
      col = (cls ~ /DAILY-DRIVER/) ? G : Y
      printf "  %s%-22s %8d %6.1f%%  %s%s\n", col, a, af[a], ap[a], cls, O
    }
  }' "$A"
printf "\n%s══ DAILY-DRIVER PRIORITY LEVERS — research-informed; weigh ALONGSIDE the raw board (undervalued by raw count) ══%s\n" "$B" "$O"
printf "  (full map + per-site deps + forecast method: %sdocs/wiki/lever-map.md%s)\n" "$C" "$O"
printf "  The board above ranks by WPT MASS and has a KNOWN BLIND SPOT: it hides cheap, boot-critical APIs whose\n"
printf "  absence BLANK-SCREENS whole SPAs. Weigh by daily-driver UNLOCK, not raw subtest count:\n"
printf "  %s⚡ BOOT-CRITICAL — do FIRST despite low WPT mass (cheap, high-gating):%s\n" "$G" "$O"
printf "     • IntersectionObserver/ResizeObserver  — x.com + Instagram feeds are DEAD without IO   (S, 402 WPT)\n"
printf "     • History / pushState                  — every SPA nav degrades to a full page reload  (S, ~1k WPT)\n"
printf "     • Proxy/Reflect + microtask/MessageChannel — Vue3 reactivity silently dead w/o Proxy    (S-M)\n"
printf "     • Fetch + ReadableStream body          — gates Next.js RSC navigation                  (M, ~19k WPT)\n"
printf "  %s⚡ STEP-FUNCTION — largest raw levers, fully daily-driver:%s\n" "$C" "$O"
printf "     • Flex/Grid intrinsic sizing (min/max-content; Taffy #204) — M-L, ~28k WPT, every site\n"
printf "     • Web fonts (@font-face / WOFF2)                           — M, 8.8k WPT, layout-metric fidelity\n"
printf "     • Shadow DOM + Custom Elements                             — L, 20k WPT, YouTube / web-components\n"
printf "  %sMSE/MEDIA is now a PHASE PRIORITY (not deferred)%s — bind GStreamer/FFmpeg, don't hand-write codecs.\n" "$G" "$O"
printf "  %sDEFER (only these)%s: compositor-threaded scrolling, CSS containment/content-visibility (low value, high cost).\n" "$Y" "$O"
printf "  %sWeight by MANUK'S OWN pass-rate (the TALLY above), never Chrome's%s: an area near 100%% HERE is a done tail,\n" "$Y" "$O"
printf "     but an area still far from 100%% here (e.g. dom) has real high-flip gaps — keep grinding those. The research's\n"
printf "     'giant is done' notes are CHROME's numbers; MANUK's measured failing subtests are ground truth and win.\n"
printf "  %sNEXT this phase%s: CSS flex/grid INTRINSIC SIZING (min/max-content, Taffy #204)  ->  more CSS layout  ->  MSE media pipeline.\n" "$G" "$O"
printf "  %sFORECAST before building%s: cluster the failing subtests by ERROR-SIGNATURE — the biggest same-signature\n" "$B" "$O"
printf "     cluster means one fix flips them all (how tick-113 landed +10,249). See docs/wiki/lever-map.md #forecast.\n"
printf "\n%sHOW TO USE (agent):%s Obey the PHASE MANDATE at the top — pick a CSS-LAYOUT (★) or MEDIA tick, NOT html/dom flip.\n" "$B" "$O"
printf "  Run \`manuk-wpt wpt css/css-flexbox --show-failures\` (or css-grid/css-sizing) for the failure histogram; the top\n"
printf "  mechanism there IS the tick. A layout fix that makes real pages render correctly beats a bigger html/dom +N.\n"
printf "  For media: there is little WPT to chase — build the MediaSource/SourceBuffer surface + a GStreamer/FFmpeg bind,\n"
printf "  and gate it with a falsifiable capability test (a sample stream buffers + plays), not a WPT count.\n"
