#!/usr/bin/env bash
# ── WIKI INDEX: regenerate docs/wiki/INDEX.md — the complete, machine-browsable map of what we KNOW.
#
# `wiki-lookup.sh` finds a section by keyword; this lists them ALL, by file, so a reader (or the next
# session, or the agent-driving horizon) can see the whole surface of accumulated knowledge at a glance
# and know what exists to be looked up. Regenerated, never hand-edited — so it cannot drift from the wiki.
#
#   scripts/wiki-index.sh          # regenerate docs/wiki/INDEX.md
#   scripts/wiki-index.sh --check  # fail if INDEX.md is stale (for CI/the wall)
set -uo pipefail
cd "$(dirname "$0")/.."
OUT=docs/wiki/INDEX.md

gen() {
  printf '# WIKI INDEX — the complete map of accumulated engine knowledge\n\n'
  printf '> **Generated by `scripts/wiki-index.sh`, never hand-edited.** Every `##` section across\n'
  printf '> `docs/wiki/` is listed here. To retrieve a section by content, use\n'
  printf '> `scripts/wiki-lookup.sh <terms>` (precise keyword match, no semantic fuzz).\n\n'
  local total=0
  for f in $(ls docs/wiki/*.md | grep -v '/INDEX.md$' | sort); do
    local title
    title=$(grep -m1 '^# ' "$f" | sed 's/^# //')
    printf '## %s\n`%s`\n\n' "${title:-$(basename "$f")}" "$f"
    # every ## / ### section heading in this file
    grep -nE '^#{2,3} ' "$f" | sed -E 's/^([0-9]+):(#{2,3}) /  - L\1 · /' \
      | sed -E 's/`//g'
    local n
    n=$(grep -cE '^#{2,3} ' "$f")
    total=$((total + n))
    printf '\n'
  done
  printf -- '---\n%s sections across %s topic files. Retrieve with `scripts/wiki-lookup.sh <terms>`.\n' \
    "$total" "$(ls docs/wiki/*.md | grep -vc '/INDEX.md$')"
}

if [ "${1:-}" = "--check" ]; then
  tmp=$(mktemp)
  gen > "$tmp"
  if ! diff -q "$tmp" "$OUT" >/dev/null 2>&1; then
    printf '✗ docs/wiki/INDEX.md is stale — run ./scripts/wiki-index.sh\n' >&2
    rm -f "$tmp"; exit 1
  fi
  rm -f "$tmp"
  printf '  ✓ wiki index current\n'
else
  gen > "$OUT"
  printf '  ✓ regenerated %s (%s sections)\n' "$OUT" "$(grep -cE '^  - L' "$OUT")"
fi
